//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists.TelekomOperations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TelekomOperationSubType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TelekomOperationSubType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.TelekomOperations.TelekomOperationSubType", typeof(TelekomOperationSubType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTTX.
        /// </summary>
        public static string FTTX {
            get {
                return ResourceManager.GetString("FTTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTTX to XDSL.
        /// </summary>
        public static string FTTX_to_XDSL {
            get {
                return ResourceManager.GetString("FTTX_to_XDSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal to Handicap.
        /// </summary>
        public static string Normal_to_Handicap {
            get {
                return ResourceManager.GetString("Normal_to_Handicap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL.
        /// </summary>
        public static string XDSL {
            get {
                return ResourceManager.GetString("XDSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL to FTTX.
        /// </summary>
        public static string XDSL_to_FTTX {
            get {
                return ResourceManager.GetString("XDSL_to_FTTX", resourceCulture);
            }
        }
    }
}
