//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Validation.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This city code already exist..
        /// </summary>
        public static string CityIDExist {
            get {
                return ResourceManager.GetString("CityIDExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City code must be a 4 digit number..
        /// </summary>
        public static string CityIDLength {
            get {
                return ResourceManager.GetString("CityIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another service by this name already exists..
        /// </summary>
        public static string ConflictError {
            get {
                return ResourceManager.GetString("ConflictError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid phone code..
        /// </summary>
        public static string CountryPhoneCode {
            get {
                return ResourceManager.GetString("CountryPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid currency value..
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a correct date..
        /// </summary>
        public static string DateBinder {
            get {
                return ResourceManager.GetString("DateBinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be days of month separated by &apos;,&apos;..
        /// </summary>
        public static string DaysOfMonth {
            get {
                return ResourceManager.GetString("DaysOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be days of week separated by &apos;,&apos;..
        /// </summary>
        public static string DaysOfWeek {
            get {
                return ResourceManager.GetString("DaysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount can not be greater than fee amount..
        /// </summary>
        public static string DiscountExceedsFeeCost {
            get {
                return ResourceManager.GetString("DiscountExceedsFeeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both shared and static IP can not be set, choose one..
        /// </summary>
        public static string DoubleIP {
            get {
                return ResourceManager.GetString("DoubleIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid prefix..
        /// </summary>
        public static string EBillPrefix {
            get {
                return ResourceManager.GetString("EBillPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is already assigned to another user..
        /// </summary>
        public static string EmailAlreadyAssigned {
            get {
                return ResourceManager.GetString("EmailAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address format is not valid..
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address already exists..
        /// </summary>
        public static string ExistingEmail {
            get {
                return ResourceManager.GetString("ExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large..
        /// </summary>
        public static string FileIsTooLarge {
            get {
                return ResourceManager.GetString("FileIsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} does not exist..
        /// </summary>
        public static string ForeignKeyNotFound {
            get {
                return ResourceManager.GetString("ForeignKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP inputs are not sufficent. Please fill them properly or leave them empty..
        /// </summary>
        public static string FUPValidation {
            get {
                return ResourceManager.GetString("FUPValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This number is already assigned to another user..
        /// </summary>
        public static string InternalNoAlreadyAssigned {
            get {
                return ResourceManager.GetString("InternalNoAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of acceptable range..
        /// </summary>
        public static string IntRange {
            get {
                return ResourceManager.GetString("IntRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input..
        /// </summary>
        public static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid call center internal numbers..
        /// </summary>
        public static string InvalidInternalIDs {
            get {
                return ResourceManager.GetString("InvalidInternalIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP range..
        /// </summary>
        public static string InvalidIPRange {
            get {
                return ResourceManager.GetString("InvalidIPRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid netmap..
        /// </summary>
        public static string InvalidNetmap {
            get {
                return ResourceManager.GetString("InvalidNetmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission selection..
        /// </summary>
        public static string InvalidPermissionSelection {
            get {
                return ResourceManager.GetString("InvalidPermissionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid package..
        /// </summary>
        public static string InvalidTelekomPacket {
            get {
                return ResourceManager.GetString("InvalidTelekomPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a valid IP address..
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a number between 1 and 1290..
        /// </summary>
        public static string IPCapacity {
            get {
                return ResourceManager.GetString("IPCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid IP subnet (255.255.255.255/32)..
        /// </summary>
        public static string IPSubnet {
            get {
                return ResourceManager.GetString("IPSubnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only contain standard letters..
        /// </summary>
        public static string LatinLetters {
            get {
                return ResourceManager.GetString("LatinLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be more than {1} characters..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max smart quota price cannot be smaller than base price..
        /// </summary>
        public static string MaxSmartQuotaPriceError {
            get {
                return ResourceManager.GetString("MaxSmartQuotaPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be less than {1} characters..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create service with no billing period..
        /// </summary>
        public static string NoBillingPeriodSelected {
            get {
                return ResourceManager.GetString("NoBillingPeriodSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create service without any domain..
        /// </summary>
        public static string NoDomainsSelected {
            get {
                return ResourceManager.GetString("NoDomainsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be 0..
        /// </summary>
        public static string NonZero {
            get {
                return ResourceManager.GetString("NonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a number..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work area is already added..
        /// </summary>
        public static string PartnerWorkAreaConflict {
            get {
                return ResourceManager.GetString("PartnerWorkAreaConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid percentage..
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid phone number..
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a number between 50 and 5000..
        /// </summary>
        public static string PortCount {
            get {
                return ResourceManager.GetString("PortCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid port number. [0-65535].
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number between 1-999,999,999..
        /// </summary>
        public static string PositiveInt {
            get {
                return ResourceManager.GetString("PositiveInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a number between 1-999,999,999,999,999,999..
        /// </summary>
        public static string PositiveLong {
            get {
                return ResourceManager.GetString("PositiveLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This province code already exist..
        /// </summary>
        public static string ProvinceIDExist {
            get {
                return ResourceManager.GetString("ProvinceIDExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} values are not valid..
        /// </summary>
        public static string RateLimit {
            get {
                return ResourceManager.GetString("RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed days in one year is 90..
        /// </summary>
        public static string ReactivationDateError {
            get {
                return ResourceManager.GetString("ReactivationDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a conflict in time table..
        /// </summary>
        public static string ServiceTimeTableConflict {
            get {
                return ResourceManager.GetString("ServiceTimeTableConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This speed code already exists..
        /// </summary>
        public static string SpeedCodeExists {
            get {
                return ResourceManager.GetString("SpeedCodeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a tax number..
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid national identification number..
        /// </summary>
        public static string TCK {
            get {
                return ResourceManager.GetString("TCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCK is not valid..
        /// </summary>
        public static string TCKCheckFailed {
            get {
                return ResourceManager.GetString("TCKCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First step TCK validation failed..
        /// </summary>
        public static string TCKValidationStep1 {
            get {
                return ResourceManager.GetString("TCKValidationStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second step TCK validation failed..
        /// </summary>
        public static string TCKValidationStep2 {
            get {
                return ResourceManager.GetString("TCKValidationStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in calling Telekom web service..
        /// </summary>
        public static string TelekomError {
            get {
                return ResourceManager.GetString("TelekomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between 00:00 and 23:59..
        /// </summary>
        public static string TimeOfDay {
            get {
                return ResourceManager.GetString("TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid time span. [hh:mm:ss].
        /// </summary>
        public static string TimeSpan {
            get {
                return ResourceManager.GetString("TimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unacceptable IP..
        /// </summary>
        public static string UnacceptableIP {
            get {
                return ResourceManager.GetString("UnacceptableIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be unique..
        /// </summary>
        public static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exists..
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only have letter and number characters..
        /// </summary>
        public static string WordAndNumber {
            get {
                return ResourceManager.GetString("WordAndNumber", resourceCulture);
            }
        }
    }
}
