//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelSpecific {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelSpecific() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Validation.ModelSpecific", typeof(ModelSpecific).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowance can not be greater than tariff fee ({0})..
        /// </summary>
        public static string AllowanceGreaterThanTariffFee {
            get {
                return ResourceManager.GetString("AllowanceGreaterThanTariffFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Domain..
        /// </summary>
        public static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Address should start with ftp:// or sftp://..
        /// </summary>
        public static string InvalidFTPAddress {
            get {
                return ResourceManager.GetString("InvalidFTPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart quota is only available for invoiced billing type..
        /// </summary>
        public static string InvalidSmartQuotaForBillingType {
            get {
                return ResourceManager.GetString("InvalidSmartQuotaForBillingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max date range is 60 days..
        /// </summary>
        public static string MaxDateRange60Days {
            get {
                return ResourceManager.GetString("MaxDateRange60Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber cannot use referral discount on the self..
        /// </summary>
        public static string SelfReferralDiscount {
            get {
                return ResourceManager.GetString("SelfReferralDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be greater than end date..
        /// </summary>
        public static string StartDateCannotBeGreaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateCannotBeGreaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This discount type is not valid for bill based discounts..
        /// </summary>
        public static string StaticDiscountNotValidForBillBaseDiscounts {
            get {
                return ResourceManager.GetString("StaticDiscountNotValidForBillBaseDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtracted amount cannot be greater than total of credits..
        /// </summary>
        public static string SubtractedAmountLessThanTotalCredits {
            get {
                return ResourceManager.GetString("SubtractedAmountLessThanTotalCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tariff already added..
        /// </summary>
        public static string TariffAlreadyAdded {
            get {
                return ResourceManager.GetString("TariffAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item must be set..
        /// </summary>
        public static string XDSLandFiberNotSelected {
            get {
                return ResourceManager.GetString("XDSLandFiberNotSelected", resourceCulture);
            }
        }
    }
}
