using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RadiusR.DB.Enums
{
    public enum PDFItemIDs
    {
        FirstName = 1,
        LastName = 2,
        MothersName = 3,
        FathersName = 4,
        BirthDate = 5,
        BirthPlace = 6,
        TCKNo = 7,
        Nationality = 8,
        Profession = 9,
        MothersMaidenName = 10,
        Sex_Male = 11,
        Sex_Female = 12,
        ContactPhoneNo = 13,
        Email = 14,
        ResidenceAddress_ProvinceName = 15,
        ResidenceAddress_DistrictName = 16,
        ResidenceAddress_NeighborhoodName = 17,
        ResidenceAddress_StreetName = 18,
        ResidenceAddress_BuildingNo = 19,
        ResidenceAddress_DoorNo = 20,
        ResidenceAddress_BuildingName = 21,
        ResidenceAddress_Floor = 22,
        ResidenceAddress_PostalCode = 41,
        ResidenceAddress_BBK = 43,
        SubscriptionAddress_ProvinceName = 23,
        SubscriptionAddress_DistrictName = 24,
        SubscriptionAddress_NeighborhoodName = 25,
        SubscriptionAddress_StreetName = 26,
        SubscriptionAddress_BuildingNo = 27,
        SubscriptionAddress_DoorNo = 28,
        SubscriptionAddress_BuildingName = 29,
        SubscriptionAddress_Floor = 30,
        SubscriptionAddress_PostalCode = 42,
        SubscriptionAddress_BBK = 44,
        PSTN = 31,
        LandPhone_Yes = 32,
        LandPhone_No = 33,
        TariffName = 34,
        CompanyTitle = 35,
        TaxOffice = 36,
        TaxNo = 37,
        TCKAndTaxNo = 63,
        FirstAndLastName = 64,
        DisplayName = 65, // First+LastName+Title
        CentralSystemNo = 38,
        TradeRegistrationNo = 39,
        BillingAddress = 40,
        Transferred_SubscriberNo = 45,
        Transferred_FirstName = 46,
        Transferred_LastName = 47,
        Transferred_FirstAndLastName = 48,
        Transferred_CompanyTitle = 49,
        Transferred_DisplayName = 50, // First+LastName+Title
        Transferred_TCKNo = 51,
        Transferred_TaxNo = 52,
        Transferred_TCKAndTaxNo = 53,
        Transferring_SubscriberNo = 54,
        Transferring_FirstName = 55,
        Transferring_LastName = 56,
        Transferring_FirstAndLastName = 57,
        Transferring_CompanyTitle = 58,
        Transferring_DisplayName = 59, // First+LastName+Title
        Transferring_TCKNo = 60,
        Transferring_TaxNo = 61,
        Transferring_TCKAndTaxNo = 62,
        XDSLNo = 66,
        SubscriberNo = 67,
        TransitionSourceOperator = 68,
    }
}
