//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.AppSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.AppSettings.CategoryNames", typeof(CategoryNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Settings.
        /// </summary>
        public static string BillSettings {
            get {
                return ResourceManager.GetString("BillSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Settings.
        /// </summary>
        public static string BTKSettings {
            get {
                return ResourceManager.GetString("BTKSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Settings.
        /// </summary>
        public static string ChartSettings {
            get {
                return ResourceManager.GetString("ChartSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Website.
        /// </summary>
        public static string CustomerWebsite {
            get {
                return ResourceManager.GetString("CustomerWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bill Credentials.
        /// </summary>
        public static string EBillCredentials {
            get {
                return ResourceManager.GetString("EBillCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bill Settings.
        /// </summary>
        public static string EBillSettings {
            get {
                return ResourceManager.GetString("EBillSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google APIs.
        /// </summary>
        public static string GoogleAPIs {
            get {
                return ResourceManager.GetString("GoogleAPIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Settings.
        /// </summary>
        public static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Settings.
        /// </summary>
        public static string TableSettings {
            get {
                return ResourceManager.GetString("TableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TürkTelekom Web Services.
        /// </summary>
        public static string TTServices {
            get {
                return ResourceManager.GetString("TTServices", resourceCulture);
            }
        }
    }
}
