//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.AppSettings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.AppSettings.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing SMS Daily Start Time.
        /// </summary>
        public static string BillSMSActTime {
            get {
                return ResourceManager.GetString("BillSMSActTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Operator Code.
        /// </summary>
        public static string BTKOperatorCode {
            get {
                return ResourceManager.GetString("BTKOperatorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Operator Name.
        /// </summary>
        public static string BTKOperatorName {
            get {
                return ResourceManager.GetString("BTKOperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Operator Type.
        /// </summary>
        public static string BTKOperatorType {
            get {
                return ResourceManager.GetString("BTKOperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear Chart Maximum Steps.
        /// </summary>
        public static string ChartMaxSteps {
            get {
                return ResourceManager.GetString("ChartMaxSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Phone Code.
        /// </summary>
        public static string CountryPhoneCode {
            get {
                return ResourceManager.GetString("CountryPhoneCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Website Registration Group.
        /// </summary>
        public static string CustomerWebsiteRegistrationGroupID {
            get {
                return ResourceManager.GetString("CustomerWebsiteRegistrationGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Password.
        /// </summary>
        public static string EBillApiPassword {
            get {
                return ResourceManager.GetString("EBillApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api Username.
        /// </summary>
        public static string EBillApiUsername {
            get {
                return ResourceManager.GetString("EBillApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Code.
        /// </summary>
        public static string EBillCompanyCode {
            get {
                return ResourceManager.GetString("EBillCompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string EBillIsActive {
            get {
                return ResourceManager.GetString("EBillIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bills Threshold.
        /// </summary>
        public static string EBillsThreshold {
            get {
                return ResourceManager.GetString("EBillsThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Tolerance (Days).
        /// </summary>
        public static string ExpirationTolerance {
            get {
                return ResourceManager.GetString("ExpirationTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geocoding API Key.
        /// </summary>
        public static string GeocodingAPIKey {
            get {
                return ResourceManager.GetString("GeocodingAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Prefix.
        /// </summary>
        public static string InvoiceArchiveIDPrefix {
            get {
                return ResourceManager.GetString("InvoiceArchiveIDPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Prefix.
        /// </summary>
        public static string InvoiceBillIDPrefix {
            get {
                return ResourceManager.GetString("InvoiceBillIDPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Host.
        /// </summary>
        public static string MailHost {
            get {
                return ResourceManager.GetString("MailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Host Port.
        /// </summary>
        public static string MailHostPort {
            get {
                return ResourceManager.GetString("MailHostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Password.
        /// </summary>
        public static string MailPass {
            get {
                return ResourceManager.GetString("MailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail User.
        /// </summary>
        public static string MailUser {
            get {
                return ResourceManager.GetString("MailUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Support Attachment Per Request.
        /// </summary>
        public static string MaxSupportAttachmentPerRequest {
            get {
                return ResourceManager.GetString("MaxSupportAttachmentPerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Support Attachment File Size.
        /// </summary>
        public static string MaxSupportAttachmentSize {
            get {
                return ResourceManager.GetString("MaxSupportAttachmentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Website Password Life.
        /// </summary>
        public static string OnlinePasswordDuration {
            get {
                return ResourceManager.GetString("OnlinePasswordDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number Count.
        /// </summary>
        public static string PagesLinkCount {
            get {
                return ResourceManager.GetString("PagesLinkCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Due Flat Penalty.
        /// </summary>
        public static string PastDueFlatPenalty {
            get {
                return ResourceManager.GetString("PastDueFlatPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Due Penalty Percentage.
        /// </summary>
        public static string PastDuePenaltyPercentage {
            get {
                return ResourceManager.GetString("PastDuePenaltyPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Tolerance (Days).
        /// </summary>
        public static string PaymentTolerance {
            get {
                return ResourceManager.GetString("PaymentTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Client Key.
        /// </summary>
        public static string RecaptchaClientKey {
            get {
                return ResourceManager.GetString("RecaptchaClientKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha Server Key.
        /// </summary>
        public static string RecaptchaServerKey {
            get {
                return ResourceManager.GetString("RecaptchaServerKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Delay.
        /// </summary>
        public static string ReviewDelay {
            get {
                return ResourceManager.GetString("ReviewDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Central System No.
        /// </summary>
        public static string SenderCentralSystemNo {
            get {
                return ResourceManager.GetString("SenderCentralSystemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender City Name.
        /// </summary>
        public static string SenderCityName {
            get {
                return ResourceManager.GetString("SenderCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Tax Region.
        /// </summary>
        public static string SenderCompanyTaxRegion {
            get {
                return ResourceManager.GetString("SenderCompanyTaxRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Company Title.
        /// </summary>
        public static string SenderCompanyTitle {
            get {
                return ResourceManager.GetString("SenderCompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Country Name.
        /// </summary>
        public static string SenderCountryName {
            get {
                return ResourceManager.GetString("SenderCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Email.
        /// </summary>
        public static string SenderEmail {
            get {
                return ResourceManager.GetString("SenderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Fax No.
        /// </summary>
        public static string SenderFaxNo {
            get {
                return ResourceManager.GetString("SenderFaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Phone No.
        /// </summary>
        public static string SenderPhoneNo {
            get {
                return ResourceManager.GetString("SenderPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Province Name.
        /// </summary>
        public static string SenderProvinceName {
            get {
                return ResourceManager.GetString("SenderProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Registration No.
        /// </summary>
        public static string SenderRegistrationNo {
            get {
                return ResourceManager.GetString("SenderRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Tax No.
        /// </summary>
        public static string SenderTaxNo {
            get {
                return ResourceManager.GetString("SenderTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email Address.
        /// </summary>
        public static string SMTPEmailAddress {
            get {
                return ResourceManager.GetString("SMTPEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email Display Email.
        /// </summary>
        public static string SMTPEmailDisplayEmail {
            get {
                return ResourceManager.GetString("SMTPEmailDisplayEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email Display Name.
        /// </summary>
        public static string SMTPEmailDisplayName {
            get {
                return ResourceManager.GetString("SMTPEmailDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email Host.
        /// </summary>
        public static string SMTPEmailHost {
            get {
                return ResourceManager.GetString("SMTPEmailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Email Password.
        /// </summary>
        public static string SMTPEmailPassword {
            get {
                return ResourceManager.GetString("SMTPEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP EMail Port.
        /// </summary>
        public static string SMTPEMailPort {
            get {
                return ResourceManager.GetString("SMTPEMailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber No. Prefix.
        /// </summary>
        public static string SubscriberNoPrefix {
            get {
                return ResourceManager.GetString("SubscriberNoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Request Reopen Allow Time.
        /// </summary>
        public static string SupportRequestReopenAllowTime {
            get {
                return ResourceManager.GetString("SupportRequestReopenAllowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Rows Count.
        /// </summary>
        public static string TableRows {
            get {
                return ResourceManager.GetString("TableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service ISP Code.
        /// </summary>
        public static string TTISPCode {
            get {
                return ResourceManager.GetString("TTISPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLO Portal Password.
        /// </summary>
        public static string TTOLOPassword {
            get {
                return ResourceManager.GetString("TTOLOPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLO Portal Username.
        /// </summary>
        public static string TTOLOUsername {
            get {
                return ResourceManager.GetString("TTOLOUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Customer Code.
        /// </summary>
        public static string TTServiceCustomerCode {
            get {
                return ResourceManager.GetString("TTServiceCustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Password.
        /// </summary>
        public static string TTServicesPassword {
            get {
                return ResourceManager.GetString("TTServicesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service Username.
        /// </summary>
        public static string TTServicesUsername {
            get {
                return ResourceManager.GetString("TTServicesUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Google Recaptcha.
        /// </summary>
        public static string UseGoogleRecaptcha {
            get {
                return ResourceManager.GetString("UseGoogleRecaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Prefix.
        /// </summary>
        public static string UsernamePrefix {
            get {
                return ResourceManager.GetString("UsernamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Suffix.
        /// </summary>
        public static string UsernameSuffix {
            get {
                return ResourceManager.GetString("UsernameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Services Infrastructure Domain.
        /// </summary>
        public static string WebsiteServicesInfrastructureDomain {
            get {
                return ResourceManager.GetString("WebsiteServicesInfrastructureDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Services Password.
        /// </summary>
        public static string WebsiteServicesPassword {
            get {
                return ResourceManager.GetString("WebsiteServicesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Services Username.
        /// </summary>
        public static string WebsiteServicesUsername {
            get {
                return ResourceManager.GetString("WebsiteServicesUsername", resourceCulture);
            }
        }
    }
}
