//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BloodTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BloodTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.BloodTypes", typeof(BloodTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB-.
        /// </summary>
        public static string ABMinus {
            get {
                return ResourceManager.GetString("ABMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AB+.
        /// </summary>
        public static string ABPlus {
            get {
                return ResourceManager.GetString("ABPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A-.
        /// </summary>
        public static string AMinus {
            get {
                return ResourceManager.GetString("AMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+.
        /// </summary>
        public static string APlus {
            get {
                return ResourceManager.GetString("APlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-.
        /// </summary>
        public static string BMinus {
            get {
                return ResourceManager.GetString("BMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B+.
        /// </summary>
        public static string BPlus {
            get {
                return ResourceManager.GetString("BPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O-.
        /// </summary>
        public static string OMinus {
            get {
                return ResourceManager.GetString("OMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O+.
        /// </summary>
        public static string OPlus {
            get {
                return ResourceManager.GetString("OPlus", resourceCulture);
            }
        }
    }
}
