//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClientAttachmentTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClientAttachmentTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.ClientAttachmentTypes", typeof(ClientAttachmentTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Certificate.
        /// </summary>
        public static string ActivityCertificate {
            get {
                return ResourceManager.GetString("ActivityCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Signitures.
        /// </summary>
        public static string AuthorizedSignitures {
            get {
                return ResourceManager.GetString("AuthorizedSignitures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Form.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHURN Form.
        /// </summary>
        public static string CHURN {
            get {
                return ResourceManager.GetString("CHURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docket.
        /// </summary>
        public static string Docket {
            get {
                return ResourceManager.GetString("Docket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Card.
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSTN Form.
        /// </summary>
        public static string PSTN {
            get {
                return ResourceManager.GetString("PSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Form.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Permit.
        /// </summary>
        public static string TaxPermit {
            get {
                return ResourceManager.GetString("TaxPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Registry Paper.
        /// </summary>
        public static string TradeRegistryPaper {
            get {
                return ResourceManager.GetString("TradeRegistryPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Form.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Form.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrant of Attorney.
        /// </summary>
        public static string WarrantOfAttorney {
            get {
                return ResourceManager.GetString("WarrantOfAttorney", resourceCulture);
            }
        }
    }
}
