//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FramedProtocol {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FramedProtocol() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.FramedProtocol", typeof(FramedProtocol).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppleTalkRemoteAccessProtocol_ARAP.
        /// </summary>
        public static string AppleTalkRemoteAccessProtocol_ARAP {
            get {
                return ResourceManager.GetString("AppleTalkRemoteAccessProtocol_ARAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GandalfProprietarySingleLinkMultiLinkProtocol.
        /// </summary>
        public static string GandalfProprietarySingleLinkMultiLinkProtocol {
            get {
                return ResourceManager.GetString("GandalfProprietarySingleLinkMultiLinkProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPRSPDPContext.
        /// </summary>
        public static string GPRSPDPContext {
            get {
                return ResourceManager.GetString("GPRSPDPContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPP.
        /// </summary>
        public static string PPP {
            get {
                return ResourceManager.GetString("PPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLIP.
        /// </summary>
        public static string SLIP {
            get {
                return ResourceManager.GetString("SLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X75Synchronous.
        /// </summary>
        public static string X75Synchronous {
            get {
                return ResourceManager.GetString("X75Synchronous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XylogicsProprietaryIPX_SLIP.
        /// </summary>
        public static string XylogicsProprietaryIPX_SLIP {
            get {
                return ResourceManager.GetString("XylogicsProprietaryIPX_SLIP", resourceCulture);
            }
        }
    }
}
