//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IDCardTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDCardTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.IDCardTypes", typeof(IDCardTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Crossing Document.
        /// </summary>
        public static string BorderCrossingDocument {
            get {
                return ResourceManager.GetString("BorderCrossingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Crew Certificate.
        /// </summary>
        public static string FlightCrewCertificate {
            get {
                return ResourceManager.GetString("FlightCrewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreigner Passport.
        /// </summary>
        public static string ForeignerPassport {
            get {
                return ResourceManager.GetString("ForeignerPassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NATO Order Document.
        /// </summary>
        public static string NATOOrderDocument {
            get {
                return ResourceManager.GetString("NATOOrderDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old TC Passport Dark Blue.
        /// </summary>
        public static string OldTCPassportDarkBlue {
            get {
                return ResourceManager.GetString("OldTCPassportDarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old TC Passport Green.
        /// </summary>
        public static string OldTCPassportGreen {
            get {
                return ResourceManager.GetString("OldTCPassportGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old TC Passport Grey.
        /// </summary>
        public static string OldTCPassportGrey {
            get {
                return ResourceManager.GetString("OldTCPassportGrey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old TC Passport Red.
        /// </summary>
        public static string OldTCPassportRed {
            get {
                return ResourceManager.GetString("OldTCPassportRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Commander Approved Personnel List.
        /// </summary>
        public static string ShipCommanderApprovedPersonnelList {
            get {
                return ResourceManager.GetString("ShipCommanderApprovedPersonnelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipman&apos;s Certificate.
        /// </summary>
        public static string ShipmansCertificate {
            get {
                return ResourceManager.GetString("ShipmansCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Birth Certificate.
        /// </summary>
        public static string TCBirthCertificate {
            get {
                return ResourceManager.GetString("TCBirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Blue Card.
        /// </summary>
        public static string TCBlueCard {
            get {
                return ResourceManager.GetString("TCBlueCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Driving Lisence.
        /// </summary>
        public static string TCDrivingLisence {
            get {
                return ResourceManager.GetString("TCDrivingLisence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Foreigner ID Card.
        /// </summary>
        public static string TCForeignerIDCard {
            get {
                return ResourceManager.GetString("TCForeignerIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC ID Card With Chip.
        /// </summary>
        public static string TCIDCardWithChip {
            get {
                return ResourceManager.GetString("TCIDCardWithChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC International Family Certificate.
        /// </summary>
        public static string TCInternationalFamilyCertificate {
            get {
                return ResourceManager.GetString("TCInternationalFamilyCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Lawyer ID Card.
        /// </summary>
        public static string TCLawyerIDCard {
            get {
                return ResourceManager.GetString("TCLawyerIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Passport Temporary.
        /// </summary>
        public static string TCPassportTemporary {
            get {
                return ResourceManager.GetString("TCPassportTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Passport With Chip.
        /// </summary>
        public static string TCPassportWithChip {
            get {
                return ResourceManager.GetString("TCPassportWithChip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Prosecutor/Judge ID Card.
        /// </summary>
        public static string TCProsecutorJudgeIDCard {
            get {
                return ResourceManager.GetString("TCProsecutorJudgeIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Temporary ID Card.
        /// </summary>
        public static string TCTemporaryIDCard {
            get {
                return ResourceManager.GetString("TCTemporaryIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Document.
        /// </summary>
        public static string TravelDocument {
            get {
                return ResourceManager.GetString("TravelDocument", resourceCulture);
            }
        }
    }
}
