//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IPBlockServiceType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IPBlockServiceType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.IPBlockServiceType", typeof(IPBlockServiceType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        public static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable.
        /// </summary>
        public static string Cable {
            get {
                return ResourceManager.GetString("Cable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial Up.
        /// </summary>
        public static string DialUp {
            get {
                return ResourceManager.GetString("DialUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        public static string Fiber {
            get {
                return ResourceManager.GetString("Fiber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Relay.
        /// </summary>
        public static string FrameRelay {
            get {
                return ResourceManager.GetString("FrameRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN.
        /// </summary>
        public static string ISDN {
            get {
                return ResourceManager.GetString("ISDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Line.
        /// </summary>
        public static string LeasedLine {
            get {
                return ResourceManager.GetString("LeasedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro Ethernet.
        /// </summary>
        public static string MetroEthernet {
            get {
                return ResourceManager.GetString("MetroEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Used.
        /// </summary>
        public static string NotUsed {
            get {
                return ResourceManager.GetString("NotUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Network.
        /// </summary>
        public static string OperatorNetwork {
            get {
                return ResourceManager.GetString("OperatorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP Relay.
        /// </summary>
        public static string SMTPRelay {
            get {
                return ResourceManager.GetString("SMTPRelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi.
        /// </summary>
        public static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wimax.
        /// </summary>
        public static string Wimax {
            get {
                return ResourceManager.GetString("Wimax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless.
        /// </summary>
        public static string Wireless {
            get {
                return ResourceManager.GetString("Wireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL.
        /// </summary>
        public static string XDSL {
            get {
                return ResourceManager.GetString("XDSL", resourceCulture);
            }
        }
    }
}
