//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PDFItemIDs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PDFItemIDs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.PDFItemIDs", typeof(PDFItemIDs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central System No.
        /// </summary>
        public static string CentralSystemNo {
            get {
                return ResourceManager.GetString("CentralSystemNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Title.
        /// </summary>
        public static string CompanyTitle {
            get {
                return ResourceManager.GetString("CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone No.
        /// </summary>
        public static string ContactPhoneNo {
            get {
                return ResourceManager.GetString("ContactPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First &amp; Last Name/Company Title.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father&apos;s Name.
        /// </summary>
        public static string FathersName {
            get {
                return ResourceManager.GetString("FathersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First &amp; Last Name.
        /// </summary>
        public static string FirstAndLastName {
            get {
                return ResourceManager.GetString("FirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Phone No.
        /// </summary>
        public static string LandPhone_No {
            get {
                return ResourceManager.GetString("LandPhone_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Phone Yes.
        /// </summary>
        public static string LandPhone_Yes {
            get {
                return ResourceManager.GetString("LandPhone_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Maiden Name.
        /// </summary>
        public static string MothersMaidenName {
            get {
                return ResourceManager.GetString("MothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Name.
        /// </summary>
        public static string MothersName {
            get {
                return ResourceManager.GetString("MothersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string Profession {
            get {
                return ResourceManager.GetString("Profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSTN.
        /// </summary>
        public static string PSTN {
            get {
                return ResourceManager.GetString("PSTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address BBK.
        /// </summary>
        public static string ResidenceAddress_BBK {
            get {
                return ResourceManager.GetString("ResidenceAddress_BBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Building Name.
        /// </summary>
        public static string ResidenceAddress_BuildingName {
            get {
                return ResourceManager.GetString("ResidenceAddress_BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Building No.
        /// </summary>
        public static string ResidenceAddress_BuildingNo {
            get {
                return ResourceManager.GetString("ResidenceAddress_BuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address District.
        /// </summary>
        public static string ResidenceAddress_DistrictName {
            get {
                return ResourceManager.GetString("ResidenceAddress_DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Door No.
        /// </summary>
        public static string ResidenceAddress_DoorNo {
            get {
                return ResourceManager.GetString("ResidenceAddress_DoorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Floor.
        /// </summary>
        public static string ResidenceAddress_Floor {
            get {
                return ResourceManager.GetString("ResidenceAddress_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Neighborhood.
        /// </summary>
        public static string ResidenceAddress_NeighborhoodName {
            get {
                return ResourceManager.GetString("ResidenceAddress_NeighborhoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Postal Code.
        /// </summary>
        public static string ResidenceAddress_PostalCode {
            get {
                return ResourceManager.GetString("ResidenceAddress_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Province.
        /// </summary>
        public static string ResidenceAddress_ProvinceName {
            get {
                return ResourceManager.GetString("ResidenceAddress_ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Address Street.
        /// </summary>
        public static string ResidenceAddress_StreetName {
            get {
                return ResourceManager.GetString("ResidenceAddress_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Sex_Female {
            get {
                return ResourceManager.GetString("Sex_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Sex_Male {
            get {
                return ResourceManager.GetString("Sex_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber No.
        /// </summary>
        public static string SubscriberNo {
            get {
                return ResourceManager.GetString("SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address BBK.
        /// </summary>
        public static string SubscriptionAddress_BBK {
            get {
                return ResourceManager.GetString("SubscriptionAddress_BBK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Building Name.
        /// </summary>
        public static string SubscriptionAddress_BuildingName {
            get {
                return ResourceManager.GetString("SubscriptionAddress_BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Building No.
        /// </summary>
        public static string SubscriptionAddress_BuildingNo {
            get {
                return ResourceManager.GetString("SubscriptionAddress_BuildingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address District.
        /// </summary>
        public static string SubscriptionAddress_DistrictName {
            get {
                return ResourceManager.GetString("SubscriptionAddress_DistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Door No.
        /// </summary>
        public static string SubscriptionAddress_DoorNo {
            get {
                return ResourceManager.GetString("SubscriptionAddress_DoorNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Floor.
        /// </summary>
        public static string SubscriptionAddress_Floor {
            get {
                return ResourceManager.GetString("SubscriptionAddress_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Neighborhood.
        /// </summary>
        public static string SubscriptionAddress_NeighborhoodName {
            get {
                return ResourceManager.GetString("SubscriptionAddress_NeighborhoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Postal Code.
        /// </summary>
        public static string SubscriptionAddress_PostalCode {
            get {
                return ResourceManager.GetString("SubscriptionAddress_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Province.
        /// </summary>
        public static string SubscriptionAddress_ProvinceName {
            get {
                return ResourceManager.GetString("SubscriptionAddress_ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Address Street.
        /// </summary>
        public static string SubscriptionAddress_StreetName {
            get {
                return ResourceManager.GetString("SubscriptionAddress_StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Name.
        /// </summary>
        public static string TariffName {
            get {
                return ResourceManager.GetString("TariffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax No.
        /// </summary>
        public static string TaxNo {
            get {
                return ResourceManager.GetString("TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Office.
        /// </summary>
        public static string TaxOffice {
            get {
                return ResourceManager.GetString("TaxOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCK/Tax No.
        /// </summary>
        public static string TCKAndTaxNo {
            get {
                return ResourceManager.GetString("TCKAndTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCK No.
        /// </summary>
        public static string TCKNo {
            get {
                return ResourceManager.GetString("TCKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Registration No.
        /// </summary>
        public static string TradeRegistrationNo {
            get {
                return ResourceManager.GetString("TradeRegistrationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Company Title.
        /// </summary>
        public static string Transferred_CompanyTitle {
            get {
                return ResourceManager.GetString("Transferred_CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred First &amp; Last Name/Company Title.
        /// </summary>
        public static string Transferred_DisplayName {
            get {
                return ResourceManager.GetString("Transferred_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred First &amp; Last Name.
        /// </summary>
        public static string Transferred_FirstAndLastName {
            get {
                return ResourceManager.GetString("Transferred_FirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred First Name.
        /// </summary>
        public static string Transferred_FirstName {
            get {
                return ResourceManager.GetString("Transferred_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Last Name.
        /// </summary>
        public static string Transferred_LastName {
            get {
                return ResourceManager.GetString("Transferred_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Subscriber No.
        /// </summary>
        public static string Transferred_SubscriberNo {
            get {
                return ResourceManager.GetString("Transferred_SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Tax No.
        /// </summary>
        public static string Transferred_TaxNo {
            get {
                return ResourceManager.GetString("Transferred_TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred TCK/Tax No.
        /// </summary>
        public static string Transferred_TCKAndTaxNo {
            get {
                return ResourceManager.GetString("Transferred_TCKAndTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred TCK No.
        /// </summary>
        public static string Transferred_TCKNo {
            get {
                return ResourceManager.GetString("Transferred_TCKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Company Title.
        /// </summary>
        public static string Transferring_CompanyTitle {
            get {
                return ResourceManager.GetString("Transferring_CompanyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring First &amp; Last Name/Company Title.
        /// </summary>
        public static string Transferring_DisplayName {
            get {
                return ResourceManager.GetString("Transferring_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring First &amp; Last Name.
        /// </summary>
        public static string Transferring_FirstAndLastName {
            get {
                return ResourceManager.GetString("Transferring_FirstAndLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring First Name.
        /// </summary>
        public static string Transferring_FirstName {
            get {
                return ResourceManager.GetString("Transferring_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Last Name.
        /// </summary>
        public static string Transferring_LastName {
            get {
                return ResourceManager.GetString("Transferring_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Subscriber No.
        /// </summary>
        public static string Transferring_SubscriberNo {
            get {
                return ResourceManager.GetString("Transferring_SubscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring Tax No.
        /// </summary>
        public static string Transferring_TaxNo {
            get {
                return ResourceManager.GetString("Transferring_TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring TCK/Tax No.
        /// </summary>
        public static string Transferring_TCKAndTaxNo {
            get {
                return ResourceManager.GetString("Transferring_TCKAndTaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring TCK No.
        /// </summary>
        public static string Transferring_TCKNo {
            get {
                return ResourceManager.GetString("Transferring_TCKNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition Source Operator.
        /// </summary>
        public static string TransitionSourceOperator {
            get {
                return ResourceManager.GetString("TransitionSourceOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL No.
        /// </summary>
        public static string XDSLNo {
            get {
                return ResourceManager.GetString("XDSLNo", resourceCulture);
            }
        }
    }
}
