//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profession {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profession() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.Profession", typeof(Profession).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officer.
        /// </summary>
        public static string Code_011 {
            get {
                return ResourceManager.GetString("Code_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent members of non-officer armed forces.
        /// </summary>
        public static string Code_021 {
            get {
                return ResourceManager.GetString("Code_021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other occupations in the armed forces.
        /// </summary>
        public static string Code_031 {
            get {
                return ResourceManager.GetString("Code_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawmakers and senior executives.
        /// </summary>
        public static string Code_111 {
            get {
                return ResourceManager.GetString("Code_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general managers and presidents (private sector).
        /// </summary>
        public static string Code_112 {
            get {
                return ResourceManager.GetString("Code_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to managers of business services and administration.
        /// </summary>
        public static string Code_121 {
            get {
                return ResourceManager.GetString("Code_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales, marketing and business development managers.
        /// </summary>
        public static string Code_122 {
            get {
                return ResourceManager.GetString("Code_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agricultural, forestry and fishery production managers.
        /// </summary>
        public static string Code_131 {
            get {
                return ResourceManager.GetString("Code_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manufacturing, mining, construction and distribution managers.
        /// </summary>
        public static string Code_132 {
            get {
                return ResourceManager.GetString("Code_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information and communication technology service managers.
        /// </summary>
        public static string Code_133 {
            get {
                return ResourceManager.GetString("Code_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professional service managers.
        /// </summary>
        public static string Code_134 {
            get {
                return ResourceManager.GetString("Code_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hotel, restaurant and restaurant managers.
        /// </summary>
        public static string Code_141 {
            get {
                return ResourceManager.GetString("Code_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retail and wholesale trade managers.
        /// </summary>
        public static string Code_142 {
            get {
                return ResourceManager.GetString("Code_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other service managers.
        /// </summary>
        public static string Code_143 {
            get {
                return ResourceManager.GetString("Code_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professional groups related to physics and earth sciences.
        /// </summary>
        public static string Code_211 {
            get {
                return ResourceManager.GetString("Code_211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mathematicians, statistics and actuaries.
        /// </summary>
        public static string Code_212 {
            get {
                return ResourceManager.GetString("Code_212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to life sciences professionals.
        /// </summary>
        public static string Code_213 {
            get {
                return ResourceManager.GetString("Code_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to professional groups related to engineering (except electrotechnical engineers).
        /// </summary>
        public static string Code_214 {
            get {
                return ResourceManager.GetString("Code_214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electrical Engineer.
        /// </summary>
        public static string Code_215 {
            get {
                return ResourceManager.GetString("Code_215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to architects, planners, surveyors and designers.
        /// </summary>
        public static string Code_216 {
            get {
                return ResourceManager.GetString("Code_216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medical doctors.
        /// </summary>
        public static string Code_221 {
            get {
                return ResourceManager.GetString("Code_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nursing and midwifery professionals.
        /// </summary>
        public static string Code_222 {
            get {
                return ResourceManager.GetString("Code_222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traditional and complementary medical professionals.
        /// </summary>
        public static string Code_223 {
            get {
                return ResourceManager.GetString("Code_223", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paramedical practitioners.
        /// </summary>
        public static string Code_224 {
            get {
                return ResourceManager.GetString("Code_224", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vets.
        /// </summary>
        public static string Code_225 {
            get {
                return ResourceManager.GetString("Code_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other health personnel.
        /// </summary>
        public static string Code_226 {
            get {
                return ResourceManager.GetString("Code_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to university and higher education faculty.
        /// </summary>
        public static string Code_231 {
            get {
                return ResourceManager.GetString("Code_231", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vocational education teachers.
        /// </summary>
        public static string Code_232 {
            get {
                return ResourceManager.GetString("Code_232", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary (secondary and high school) teachers.
        /// </summary>
        public static string Code_233 {
            get {
                return ResourceManager.GetString("Code_233", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primary and pre-school teachers.
        /// </summary>
        public static string Code_234 {
            get {
                return ResourceManager.GetString("Code_234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other professionals of education.
        /// </summary>
        public static string Code_235 {
            get {
                return ResourceManager.GetString("Code_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finance professionals.
        /// </summary>
        public static string Code_241 {
            get {
                return ResourceManager.GetString("Code_241", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to management professionals.
        /// </summary>
        public static string Code_242 {
            get {
                return ResourceManager.GetString("Code_242", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales, marketing and public relations professionals.
        /// </summary>
        public static string Code_243 {
            get {
                return ResourceManager.GetString("Code_243", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to software and application developers and analysts.
        /// </summary>
        public static string Code_251 {
            get {
                return ResourceManager.GetString("Code_251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to database and computer networks professionals.
        /// </summary>
        public static string Code_252 {
            get {
                return ResourceManager.GetString("Code_252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to law professionals.
        /// </summary>
        public static string Code_261 {
            get {
                return ResourceManager.GetString("Code_261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to librarians, archivists and curators.
        /// </summary>
        public static string Code_262 {
            get {
                return ResourceManager.GetString("Code_262", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social and religious professionals.
        /// </summary>
        public static string Code_263 {
            get {
                return ResourceManager.GetString("Code_263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writers, journalists and linguists.
        /// </summary>
        public static string Code_264 {
            get {
                return ResourceManager.GetString("Code_264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to creative artists and stage artists.
        /// </summary>
        public static string Code_265 {
            get {
                return ResourceManager.GetString("Code_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physics and engineering science technicians.
        /// </summary>
        public static string Code_311 {
            get {
                return ResourceManager.GetString("Code_311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mining, manufacturing and construction supervisors.
        /// </summary>
        public static string Code_312 {
            get {
                return ResourceManager.GetString("Code_312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process control technicians.
        /// </summary>
        public static string Code_313 {
            get {
                return ResourceManager.GetString("Code_313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to life sciences and technicians and related assistants.
        /// </summary>
        public static string Code_314 {
            get {
                return ResourceManager.GetString("Code_314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship and aircraft controllers and technicians.
        /// </summary>
        public static string Code_315 {
            get {
                return ResourceManager.GetString("Code_315", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medical technicians and pharmaceutical technicians.
        /// </summary>
        public static string Code_321 {
            get {
                return ResourceManager.GetString("Code_321", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nursing and midwifery assisting professionals.
        /// </summary>
        public static string Code_322 {
            get {
                return ResourceManager.GetString("Code_322", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helping professionals in traditional and complementary medicine.
        /// </summary>
        public static string Code_323 {
            get {
                return ResourceManager.GetString("Code_323", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to veterinary technicians and assistants.
        /// </summary>
        public static string Code_324 {
            get {
                return ResourceManager.GetString("Code_324", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other auxiliary health personnel.
        /// </summary>
        public static string Code_325 {
            get {
                return ResourceManager.GetString("Code_325", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to associate professionals in finance and mathematical affairs.
        /// </summary>
        public static string Code_331 {
            get {
                return ResourceManager.GetString("Code_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sales and purchasing agents and brokers.
        /// </summary>
        public static string Code_332 {
            get {
                return ResourceManager.GetString("Code_332", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to business services agents.
        /// </summary>
        public static string Code_333 {
            get {
                return ResourceManager.GetString("Code_333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secretaries specializing in administrative and specific areas.
        /// </summary>
        public static string Code_334 {
            get {
                return ResourceManager.GetString("Code_334", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adjunct professionals in regulatory state related areas.
        /// </summary>
        public static string Code_335 {
            get {
                return ResourceManager.GetString("Code_335", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legal, social and dim related professionals.
        /// </summary>
        public static string Code_341 {
            get {
                return ResourceManager.GetString("Code_341", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sports and fitness workers.
        /// </summary>
        public static string Code_342 {
            get {
                return ResourceManager.GetString("Code_342", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to art, culture and culinary professionals.
        /// </summary>
        public static string Code_343 {
            get {
                return ResourceManager.GetString("Code_343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information and communication technologies operating and user support technicians.
        /// </summary>
        public static string Code_351 {
            get {
                return ResourceManager.GetString("Code_351", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telecommunications and broadcast technicians.
        /// </summary>
        public static string Code_352 {
            get {
                return ResourceManager.GetString("Code_352", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general office staff.
        /// </summary>
        public static string Code_411 {
            get {
                return ResourceManager.GetString("Code_411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secretaries (general).
        /// </summary>
        public static string Code_412 {
            get {
                return ResourceManager.GetString("Code_412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operators using keyboards.
        /// </summary>
        public static string Code_413 {
            get {
                return ResourceManager.GetString("Code_413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cashiers, collectors and similar staff.
        /// </summary>
        public static string Code_421 {
            get {
                return ResourceManager.GetString("Code_421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer advisory staff.
        /// </summary>
        public static string Code_422 {
            get {
                return ResourceManager.GetString("Code_422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to office staff.
        /// </summary>
        public static string Code_431 {
            get {
                return ResourceManager.GetString("Code_431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to office personnel for material records and transportation.
        /// </summary>
        public static string Code_432 {
            get {
                return ResourceManager.GetString("Code_432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other office services.
        /// </summary>
        public static string Code_441 {
            get {
                return ResourceManager.GetString("Code_441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to travel staff, conductors and bus assistants and guides.
        /// </summary>
        public static string Code_511 {
            get {
                return ResourceManager.GetString("Code_511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cooks.
        /// </summary>
        public static string Code_512 {
            get {
                return ResourceManager.GetString("Code_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiters and bartenders.
        /// </summary>
        public static string Code_513 {
            get {
                return ResourceManager.GetString("Code_513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hairdressers, beauticians and related workers.
        /// </summary>
        public static string Code_514 {
            get {
                return ResourceManager.GetString("Code_514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to building and cleaning and maintenance.
        /// </summary>
        public static string Code_515 {
            get {
                return ResourceManager.GetString("Code_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other personal services.
        /// </summary>
        public static string Code_516 {
            get {
                return ResourceManager.GetString("Code_516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street, bench and market salespeople.
        /// </summary>
        public static string Code_521 {
            get {
                return ResourceManager.GetString("Code_521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store, shop etc. sales staff.
        /// </summary>
        public static string Code_522 {
            get {
                return ResourceManager.GetString("Code_522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cashiers and ticket sellers.
        /// </summary>
        public static string Code_523 {
            get {
                return ResourceManager.GetString("Code_523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other salespersons.
        /// </summary>
        public static string Code_524 {
            get {
                return ResourceManager.GetString("Code_524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to child care services and teacher assistants.
        /// </summary>
        public static string Code_531 {
            get {
                return ResourceManager.GetString("Code_531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal care workers in health care.
        /// </summary>
        public static string Code_532 {
            get {
                return ResourceManager.GetString("Code_532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personnel providing protection services.
        /// </summary>
        public static string Code_541 {
            get {
                return ResourceManager.GetString("Code_541", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gardeners and plant growers.
        /// </summary>
        public static string Code_611 {
            get {
                return ResourceManager.GetString("Code_611", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to animal breeders.
        /// </summary>
        public static string Code_612 {
            get {
                return ResourceManager.GetString("Code_612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forestry and forestry workers.
        /// </summary>
        public static string Code_621 {
            get {
                return ResourceManager.GetString("Code_621", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aquaculture workers, hunters and traps.
        /// </summary>
        public static string Code_622 {
            get {
                return ResourceManager.GetString("Code_622", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to herbalist growers.
        /// </summary>
        public static string Code_631 {
            get {
                return ResourceManager.GetString("Code_631", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to livestock growers.
        /// </summary>
        public static string Code_632 {
            get {
                return ResourceManager.GetString("Code_632", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mixed crops and livestock growers for their livelihoods.
        /// </summary>
        public static string Code_633 {
            get {
                return ResourceManager.GetString("Code_633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fishermen, hunters, trappers and gatherers for their livelihood.
        /// </summary>
        public static string Code_634 {
            get {
                return ResourceManager.GetString("Code_634", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to craftsmen.
        /// </summary>
        public static string Code_711 {
            get {
                return ResourceManager.GetString("Code_711", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to construction works and craftsmen.
        /// </summary>
        public static string Code_712 {
            get {
                return ResourceManager.GetString("Code_712", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whitewash, paint and building exterior cleaning and related workers.
        /// </summary>
        public static string Code_713 {
            get {
                return ResourceManager.GetString("Code_713", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metal sheet and construction material, metal molders and welders and related workers.
        /// </summary>
        public static string Code_721 {
            get {
                return ResourceManager.GetString("Code_721", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blacksmiths, tool makers and related workers.
        /// </summary>
        public static string Code_722 {
            get {
                return ResourceManager.GetString("Code_722", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machinery maintenance and repair.
        /// </summary>
        public static string Code_723 {
            get {
                return ResourceManager.GetString("Code_723", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crafts employees.
        /// </summary>
        public static string Code_731 {
            get {
                return ResourceManager.GetString("Code_731", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to print workers.
        /// </summary>
        public static string Code_732 {
            get {
                return ResourceManager.GetString("Code_732", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electrical equipment dealers and repairers.
        /// </summary>
        public static string Code_741 {
            get {
                return ResourceManager.GetString("Code_741", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to electronic and telecommunications agencies and repairers.
        /// </summary>
        public static string Code_742 {
            get {
                return ResourceManager.GetString("Code_742", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to food processing and related workers.
        /// </summary>
        public static string Code_751 {
            get {
                return ResourceManager.GetString("Code_751", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woodworking, wood furniture manufacturers and related workers.
        /// </summary>
        public static string Code_752 {
            get {
                return ResourceManager.GetString("Code_752", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textile and clothing.
        /// </summary>
        public static string Code_753 {
            get {
                return ResourceManager.GetString("Code_753", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other craftsmen and related workers.
        /// </summary>
        public static string Code_754 {
            get {
                return ResourceManager.GetString("Code_754", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mining and mineral processing plant operators.
        /// </summary>
        public static string Code_811 {
            get {
                return ResourceManager.GetString("Code_811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chemical and photographic products plant and machinery operators.
        /// </summary>
        public static string Code_813 {
            get {
                return ResourceManager.GetString("Code_813", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machine operators of rubber, plastic and paper products.
        /// </summary>
        public static string Code_814 {
            get {
                return ResourceManager.GetString("Code_814", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to textile, fur and leather machine operators.
        /// </summary>
        public static string Code_815 {
            get {
                return ResourceManager.GetString("Code_815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machine operators of food-related products.
        /// </summary>
        public static string Code_816 {
            get {
                return ResourceManager.GetString("Code_816", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to woodworking and paper manufacturing plant operators.
        /// </summary>
        public static string Code_817 {
            get {
                return ResourceManager.GetString("Code_817", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other stationary and machine operators.
        /// </summary>
        public static string Code_818 {
            get {
                return ResourceManager.GetString("Code_818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to installers.
        /// </summary>
        public static string Code_821 {
            get {
                return ResourceManager.GetString("Code_821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locomotive engine drivers and related workers.
        /// </summary>
        public static string Code_831 {
            get {
                return ResourceManager.GetString("Code_831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drivers of cars, vans and motorcycles.
        /// </summary>
        public static string Code_832 {
            get {
                return ResourceManager.GetString("Code_832", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to heavy duty truck and bus drivers.
        /// </summary>
        public static string Code_833 {
            get {
                return ResourceManager.GetString("Code_833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile machinery and equipment operators.
        /// </summary>
        public static string Code_834 {
            get {
                return ResourceManager.GetString("Code_834", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ship deck crews and related workers.
        /// </summary>
        public static string Code_835 {
            get {
                return ResourceManager.GetString("Code_835", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cleaners and household chores working in homes, hotels and offices.
        /// </summary>
        public static string Code_911 {
            get {
                return ResourceManager.GetString("Code_911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicle and window cleaning, laundry and other manual cleaning.
        /// </summary>
        public static string Code_912 {
            get {
                return ResourceManager.GetString("Code_912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agricultural, forestry and fishery sectors.
        /// </summary>
        public static string Code_921 {
            get {
                return ResourceManager.GetString("Code_921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-qualified workers in the mining and construction sectors.
        /// </summary>
        public static string Code_931 {
            get {
                return ResourceManager.GetString("Code_931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-qualified workers in manufacturing.
        /// </summary>
        public static string Code_932 {
            get {
                return ResourceManager.GetString("Code_932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-qualified workers in the transport and storage sectors.
        /// </summary>
        public static string Code_933 {
            get {
                return ResourceManager.GetString("Code_933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to food preparation aids.
        /// </summary>
        public static string Code_941 {
            get {
                return ResourceManager.GetString("Code_941", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street and street service workers.
        /// </summary>
        public static string Code_951 {
            get {
                return ResourceManager.GetString("Code_951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to street vendors (excluding food).
        /// </summary>
        public static string Code_952 {
            get {
                return ResourceManager.GetString("Code_952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scavengers and waste collectors.
        /// </summary>
        public static string Code_961 {
            get {
                return ResourceManager.GetString("Code_961", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other non-qualified employees.
        /// </summary>
        public static string Code_962 {
            get {
                return ResourceManager.GetString("Code_962", resourceCulture);
            }
        }
    }
}
