//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceInfrastuctureTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceInfrastuctureTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.ServiceInfrastuctureTypes", typeof(ServiceInfrastuctureTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADSL.
        /// </summary>
        public static string ADSL {
            get {
                return ResourceManager.GetString("ADSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin Box.
        /// </summary>
        public static string ANKESOR {
            get {
                return ResourceManager.GetString("ANKESOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM.
        /// </summary>
        public static string ATM {
            get {
                return ResourceManager.GetString("ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centrex.
        /// </summary>
        public static string CENTREKS {
            get {
                return ResourceManager.GetString("CENTREKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiber.
        /// </summary>
        public static string FIBER {
            get {
                return ResourceManager.GetString("FIBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        public static string FR {
            get {
                return ResourceManager.GetString("FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Phone.
        /// </summary>
        public static string GORUNTULU_TELEFON {
            get {
                return ResourceManager.GetString("GORUNTULU_TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSMPOS.
        /// </summary>
        public static string GSMPOS {
            get {
                return ResourceManager.GetString("GSMPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiper.
        /// </summary>
        public static string HIPER {
            get {
                return ResourceManager.GetString("HIPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSCSD.
        /// </summary>
        public static string HSCSD {
            get {
                return ResourceManager.GetString("HSCSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi IP Line.
        /// </summary>
        public static string IP_COKLU_HAT {
            get {
                return ResourceManager.GetString("IP_COKLU_HAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi IP Service 444.
        /// </summary>
        public static string IP_COKLU_SERVIS_444 {
            get {
                return ResourceManager.GetString("IP_COKLU_SERVIS_444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN Cloud Academy.
        /// </summary>
        public static string ISDN_BULUT_AKADEMI {
            get {
                return ResourceManager.GetString("ISDN_BULUT_AKADEMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISDN PRI.
        /// </summary>
        public static string ISDN_PRI {
            get {
                return ResourceManager.GetString("ISDN_PRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kable Net.
        /// </summary>
        public static string KABLONET {
            get {
                return ResourceManager.GetString("KABLONET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Line Data.
        /// </summary>
        public static string KIRALIK_DEVRE_DATA {
            get {
                return ResourceManager.GetString("KIRALIK_DEVRE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Line Partial.
        /// </summary>
        public static string KIRALIK_DEVRE_KISMI {
            get {
                return ResourceManager.GetString("KIRALIK_DEVRE_KISMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Line Phone.
        /// </summary>
        public static string KIRALIK_DEVRE_TELEFON {
            get {
                return ResourceManager.GetString("KIRALIK_DEVRE_TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leased Line Telegraph.
        /// </summary>
        public static string KIRALIK_DEVRE_TELEGRAF {
            get {
                return ResourceManager.GetString("KIRALIK_DEVRE_TELEGRAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Security.
        /// </summary>
        public static string KURUMSAL_GUVENLIK {
            get {
                return ResourceManager.GetString("KURUMSAL_GUVENLIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro.
        /// </summary>
        public static string METRO {
            get {
                return ResourceManager.GetString("METRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia Coin Box.
        /// </summary>
        public static string MULTIMEDYA_ANKESOR {
            get {
                return ResourceManager.GetString("MULTIMEDYA_ANKESOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P ADSL.
        /// </summary>
        public static string P2P_ADSL {
            get {
                return ResourceManager.GetString("P2P_ADSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P ATM.
        /// </summary>
        public static string P2P_ATM {
            get {
                return ResourceManager.GetString("P2P_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P FR.
        /// </summary>
        public static string P2P_FR {
            get {
                return ResourceManager.GetString("P2P_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P GHDSL.
        /// </summary>
        public static string P2P_GHDSL {
            get {
                return ResourceManager.GetString("P2P_GHDSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P2P Metro.
        /// </summary>
        public static string P2P_METRO {
            get {
                return ResourceManager.GetString("P2P_METRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpaid GSM.
        /// </summary>
        public static string POSTPAID_GSM {
            get {
                return ResourceManager.GetString("POSTPAID_GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpaid Internet.
        /// </summary>
        public static string POSTPAID_INTERNET {
            get {
                return ResourceManager.GetString("POSTPAID_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postpaid M2M.
        /// </summary>
        public static string POSTPAID_M2M {
            get {
                return ResourceManager.GetString("POSTPAID_M2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid GSM.
        /// </summary>
        public static string PREPAID_GSM {
            get {
                return ResourceManager.GetString("PREPAID_GSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid Internet.
        /// </summary>
        public static string PREPAID_INTERNET {
            get {
                return ResourceManager.GetString("PREPAID_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid M2M.
        /// </summary>
        public static string PREPAID_M2M {
            get {
                return ResourceManager.GetString("PREPAID_M2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Line.
        /// </summary>
        public static string SABIT_HAT {
            get {
                return ResourceManager.GetString("SABIT_HAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Switchboard.
        /// </summary>
        public static string SANAL_SANTRAL {
            get {
                return ResourceManager.GetString("SANAL_SANTRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Multiline.
        /// </summary>
        public static string SAYISAL_COKLU_HAT {
            get {
                return ResourceManager.GetString("SAYISAL_COKLU_HAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Multi Service 3 Digits.
        /// </summary>
        public static string SAYISAL_COKLU_SERVIS_3RAKAM {
            get {
                return ResourceManager.GetString("SAYISAL_COKLU_SERVIS_3RAKAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Multi Service 444.
        /// </summary>
        public static string SAYISAL_COKLU_SERVIS_444 {
            get {
                return ResourceManager.GetString("SAYISAL_COKLU_SERVIS_444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Multi Service 800.
        /// </summary>
        public static string SAYISAL_COKLU_SERVIS_800 {
            get {
                return ResourceManager.GetString("SAYISAL_COKLU_SERVIS_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Multi Service 822.
        /// </summary>
        public static string SAYISAL_COKLU_SERVIS_822 {
            get {
                return ResourceManager.GetString("SAYISAL_COKLU_SERVIS_822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Double Line.
        /// </summary>
        public static string SAYISAL_IKILI_HAT {
            get {
                return ResourceManager.GetString("SAYISAL_IKILI_HAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 3 Digits.
        /// </summary>
        public static string SERVIS_3RAKAM {
            get {
                return ResourceManager.GetString("SERVIS_3RAKAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 444.
        /// </summary>
        public static string SERVIS_444 {
            get {
                return ResourceManager.GetString("SERVIS_444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service 800.
        /// </summary>
        public static string SERVIS_800 {
            get {
                return ResourceManager.GetString("SERVIS_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSG Internet.
        /// </summary>
        public static string SSG_INTERNET {
            get {
                return ResourceManager.GetString("SSG_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TELEFON {
            get {
                return ResourceManager.GetString("TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telex.
        /// </summary>
        public static string TELEKS {
            get {
                return ResourceManager.GetString("TELEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TES Satellite IP &amp; Phone.
        /// </summary>
        public static string TES_UYDU_IP_VE_TELEFON {
            get {
                return ResourceManager.GetString("TES_UYDU_IP_VE_TELEFON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Data.
        /// </summary>
        public static string UYDU_DATA {
            get {
                return ResourceManager.GetString("UYDU_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Internet.
        /// </summary>
        public static string UYDU_INTERNET {
            get {
                return ResourceManager.GetString("UYDU_INTERNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Audio.
        /// </summary>
        public static string UYDU_SES {
            get {
                return ResourceManager.GetString("UYDU_SES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Center.
        /// </summary>
        public static string VERI_MERKEZI {
            get {
                return ResourceManager.GetString("VERI_MERKEZI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN ADSL.
        /// </summary>
        public static string VPN_ADSL {
            get {
                return ResourceManager.GetString("VPN_ADSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN FR.
        /// </summary>
        public static string VPN_FR {
            get {
                return ResourceManager.GetString("VPN_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN GHDSL.
        /// </summary>
        public static string VPN_GHDSL {
            get {
                return ResourceManager.GetString("VPN_GHDSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN Metro.
        /// </summary>
        public static string VPN_METRO {
            get {
                return ResourceManager.GetString("VPN_METRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIFI.
        /// </summary>
        public static string WIFI {
            get {
                return ResourceManager.GetString("WIFI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIMAX.
        /// </summary>
        public static string WIMAX {
            get {
                return ResourceManager.GetString("WIMAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XDSL.
        /// </summary>
        public static string XDSL {
            get {
                return ResourceManager.GetString("XDSL", resourceCulture);
            }
        }
    }
}
