//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemLogTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemLogTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.SystemLogTypes", typeof(SystemLogTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Automatic Payment.
        /// </summary>
        public static string ActivateAutomaticPayment {
            get {
                return ResourceManager.GetString("ActivateAutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Additional Fee.
        /// </summary>
        public static string AddAdditionalFee {
            get {
                return ResourceManager.GetString("AddAdditionalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit Card.
        /// </summary>
        public static string AddCreditCard {
            get {
                return ResourceManager.GetString("AddCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Recurring Discount.
        /// </summary>
        public static string AddRecurringDiscount {
            get {
                return ResourceManager.GetString("AddRecurringDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Change.
        /// </summary>
        public static string AddressChange {
            get {
                return ResourceManager.GetString("AddressChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Subscription.
        /// </summary>
        public static string AddSubscription {
            get {
                return ResourceManager.GetString("AddSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Work Order.
        /// </summary>
        public static string AddWorkOrder {
            get {
                return ResourceManager.GetString("AddWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Payment.
        /// </summary>
        public static string BillPayment {
            get {
                return ResourceManager.GetString("BillPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Additional Fee.
        /// </summary>
        public static string CancelAdditionalFee {
            get {
                return ResourceManager.GetString("CancelAdditionalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Cancellation.
        /// </summary>
        public static string CancelBill {
            get {
                return ResourceManager.GetString("CancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Payment.
        /// </summary>
        public static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Change Tariff Cancellation.
        /// </summary>
        public static string CancelScheduledChangeService {
            get {
                return ResourceManager.GetString("CancelScheduledChangeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Client State.
        /// </summary>
        public static string ChangeClientState {
            get {
                return ResourceManager.GetString("ChangeClientState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Customer Info.
        /// </summary>
        public static string ChangeCustomer {
            get {
                return ResourceManager.GetString("ChangeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Installation Address.
        /// </summary>
        public static string ChangeInstallationAddress {
            get {
                return ResourceManager.GetString("ChangeInstallationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Expiration Date.
        /// </summary>
        public static string ChangeLastAllowedDate {
            get {
                return ResourceManager.GetString("ChangeLastAllowedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Service.
        /// </summary>
        public static string ChangeService {
            get {
                return ResourceManager.GetString("ChangeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Change Tariff.
        /// </summary>
        public static string ChangeServiceSchedule {
            get {
                return ResourceManager.GetString("ChangeServiceSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Info.
        /// </summary>
        public static string ChangeSubscriber {
            get {
                return ResourceManager.GetString("ChangeSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber DSLNo.
        /// </summary>
        public static string ChangeSubscriberDSLNo {
            get {
                return ResourceManager.GetString("ChangeSubscriberDSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Groups.
        /// </summary>
        public static string ChangeSubscriberGroup {
            get {
                return ResourceManager.GetString("ChangeSubscriberGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Password.
        /// </summary>
        public static string ChangeSubscriberPassword {
            get {
                return ResourceManager.GetString("ChangeSubscriberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Static IP.
        /// </summary>
        public static string ChangeSubscriberStaticIP {
            get {
                return ResourceManager.GetString("ChangeSubscriberStaticIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Username.
        /// </summary>
        public static string ChangeSubscriberUsername {
            get {
                return ResourceManager.GetString("ChangeSubscriberUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Subscriber Speed Profile.
        /// </summary>
        public static string ChangeSubscriptionSpeedProfile {
            get {
                return ResourceManager.GetString("ChangeSubscriptionSpeedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Telekom Work Order.
        /// </summary>
        public static string CloseTelekomWorkOrder {
            get {
                return ResourceManager.GetString("CloseTelekomWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Work Order.
        /// </summary>
        public static string CloseWorkOrder {
            get {
                return ResourceManager.GetString("CloseWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Telekom Work Order.
        /// </summary>
        public static string CreateTelekomWorkOrder {
            get {
                return ResourceManager.GetString("CreateTelekomWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate Automatic Payment.
        /// </summary>
        public static string DeactivateAutomaticPayment {
            get {
                return ResourceManager.GetString("DeactivateAutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Recurring Discount.
        /// </summary>
        public static string DisableRecurringDiscount {
            get {
                return ResourceManager.GetString("DisableRecurringDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client Identity Document.
        /// </summary>
        public static string EditClientIdentityDocument {
            get {
                return ResourceManager.GetString("EditClientIdentityDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Discount.
        /// </summary>
        public static string EditDiscount {
            get {
                return ResourceManager.GetString("EditDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Subscriber Commitment.
        /// </summary>
        public static string EditSubscriberCommitment {
            get {
                return ResourceManager.GetString("EditSubscriberCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Extention.
        /// </summary>
        public static string ExtendPackage {
            get {
                return ResourceManager.GetString("ExtendPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Change Service.
        /// </summary>
        public static string ForceChangeService {
            get {
                return ResourceManager.GetString("ForceChangeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Quality Check.
        /// </summary>
        public static string LineQualityCheck {
            get {
                return ResourceManager.GetString("LineQualityCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Additional Fee.
        /// </summary>
        public static string RemoveAdditionalFee {
            get {
                return ResourceManager.GetString("RemoveAdditionalFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Credit Card.
        /// </summary>
        public static string RemoveCreditCard {
            get {
                return ResourceManager.GetString("RemoveCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove File.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Recurring Discount.
        /// </summary>
        public static string RemoveRecurringDiscount {
            get {
                return ResourceManager.GetString("RemoveRecurringDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Work Order.
        /// </summary>
        public static string RemoveWorkOrder {
            get {
                return ResourceManager.GetString("RemoveWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry Telekom Work Order.
        /// </summary>
        public static string RetryTelekomWorkOrder {
            get {
                return ResourceManager.GetString("RetryTelekomWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Sale.
        /// </summary>
        public static string SellQuota {
            get {
                return ResourceManager.GetString("SellQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Down Subscriber Speed Profile.
        /// </summary>
        public static string StepDownSubscriptionSpeedProfile {
            get {
                return ResourceManager.GetString("StepDownSubscriptionSpeedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step Up Subscriber Speed Profile.
        /// </summary>
        public static string StepUpSubscriptionSpeedProfile {
            get {
                return ResourceManager.GetString("StepUpSubscriptionSpeedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Transfer Application.
        /// </summary>
        public static string SubscriptionTransferApplied {
            get {
                return ResourceManager.GetString("SubscriptionTransferApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Sync.
        /// </summary>
        public static string TelekomSync {
            get {
                return ResourceManager.GetString("TelekomSync", resourceCulture);
            }
        }
    }
}
