//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemLogInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemLogInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.SystemLogInterface", typeof(SystemLogInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Payment Web Service.
        /// </summary>
        public static string BankPaymentWebService {
            get {
                return ResourceManager.GetString("BankPaymentWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Website.
        /// </summary>
        public static string CustomerWebsite {
            get {
                return ResourceManager.GetString("CustomerWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Site Service.
        /// </summary>
        public static string MainSiteService {
            get {
                return ResourceManager.GetString("MainSiteService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MasterISS.
        /// </summary>
        public static string MasterISS {
            get {
                return ResourceManager.GetString("MasterISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Web Service.
        /// </summary>
        public static string PartnerWebService {
            get {
                return ResourceManager.GetString("PartnerWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string RadiusRScheduler {
            get {
                return ResourceManager.GetString("RadiusRScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RADIUS-R Server.
        /// </summary>
        public static string RadiusRServer {
            get {
                return ResourceManager.GetString("RadiusRServer", resourceCulture);
            }
        }
    }
}
