//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TTWorkType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TTWorkType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.TTWorkType", typeof(TTWorkType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Naked.
        /// </summary>
        public static string ChangeToNaked {
            get {
                return ResourceManager.GetString("ChangeToNaked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISP Change.
        /// </summary>
        public static string ISPChange {
            get {
                return ResourceManager.GetString("ISPChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale (DSL).
        /// </summary>
        public static string Sale_DSL {
            get {
                return ResourceManager.GetString("Sale_DSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale (FTTX).
        /// </summary>
        public static string Sale_FTTX {
            get {
                return ResourceManager.GetString("Sale_FTTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tariff Change.
        /// </summary>
        public static string TariffChange {
            get {
                return ResourceManager.GetString("TariffChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport (DSL).
        /// </summary>
        public static string Transport_DSL {
            get {
                return ResourceManager.GetString("Transport_DSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport (FTTX).
        /// </summary>
        public static string Transport_FTTX {
            get {
                return ResourceManager.GetString("Transport_FTTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Change.
        /// </summary>
        public static string TypeChange {
            get {
                return ResourceManager.GetString("TypeChange", resourceCulture);
            }
        }
    }
}
