//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Lists.CustomerSetup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FaultCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FaultCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Lists.CustomerSetup.FaultCodes", typeof(FaultCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Installation Fault.
        /// </summary>
        public static string BuildingInstallationFault {
            get {
                return ResourceManager.GetString("BuildingInstallationFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Cancelled.
        /// </summary>
        public static string ClientCancelled {
            get {
                return ResourceManager.GetString("ClientCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Could Not Be Reached.
        /// </summary>
        public static string CustomerCouldNotBeReached {
            get {
                return ResourceManager.GetString("CustomerCouldNotBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Did The Setup.
        /// </summary>
        public static string CustomerDidTheSetup {
            get {
                return ResourceManager.GetString("CustomerDidTheSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Address.
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modem Fault.
        /// </summary>
        public static string ModemFault {
            get {
                return ResourceManager.GetString("ModemFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Problem.
        /// </summary>
        public static string NoFault {
            get {
                return ResourceManager.GetString("NoFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rendezvous Made.
        /// </summary>
        public static string RendezvousMade {
            get {
                return ResourceManager.GetString("RendezvousMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Complete.
        /// </summary>
        public static string SetupComplete {
            get {
                return ResourceManager.GetString("SetupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom General Fault.
        /// </summary>
        public static string TelekomGeneralFault {
            get {
                return ResourceManager.GetString("TelekomGeneralFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Line Fault.
        /// </summary>
        public static string TelekomLineFault {
            get {
                return ResourceManager.GetString("TelekomLineFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting For New Rendezvous.
        /// </summary>
        public static string WaitingForNewRendezvous {
            get {
                return ResourceManager.GetString("WaitingForNewRendezvous", resourceCulture);
            }
        }
    }
}
