//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Pages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successfull.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove service while users are attached to it..
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer has unpaid bills..
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency value is not valid or details is empty..
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have enough credits..
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This technician does not exist..
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This work order does not exist..
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This support request does not exist..
        /// </summary>
        public static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NAS does not exist..
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client have usage records and can not be deleted..
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group does not exist..
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router error..
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tariff does not exist..
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NAS does not exist..
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This note does not exist..
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove NAS while users are attached to it..
        /// </summary>
        public static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist..
        /// </summary>
        public static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role does not exist..
        /// </summary>
        public static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove dealer while it has relative data..
        /// </summary>
        public static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cashier does not exist..
        /// </summary>
        public static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove cashier while it has relative data..
        /// </summary>
        public static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove province while it has relative data..
        /// </summary>
        public static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove city while it has relative data..
        /// </summary>
        public static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dealer does not exist..
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment session is expired..
        /// </summary>
        public static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS message validation failed..
        /// </summary>
        public static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBK and PSTN cannot be both empty..
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving data from web service..
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficent registration info..
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file..
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open support request already exists..
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain type..
        /// </summary>
        public static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This customer does not exist..
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid customer state..
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This fee does not exist..
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not remove fee while there are bills attached to it..
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This bill does not exist..
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid operation..
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
    }
}
