//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OfflinePaymentReportStages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OfflinePaymentReportStages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Pages.OfflinePaymentReportStages", typeof(OfflinePaymentReportStages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No {0} For Subscription {1} Already Paid..
        /// </summary>
        public static string AlreadyPaidBill {
            get {
                return ResourceManager.GetString("AlreadyPaidBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No {0} Not Found..
        /// </summary>
        public static string BillNotFound {
            get {
                return ResourceManager.GetString("BillNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Payment.
        /// </summary>
        public static string BillPayment {
            get {
                return ResourceManager.GetString("BillPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Upload File From Database.
        /// </summary>
        public static string CreateUploadFileFromDatabase {
            get {
                return ResourceManager.GetString("CreateUploadFileFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Payment For Bill No: {0}, Subscriber No: {1}..
        /// </summary>
        public static string FailedPayment {
            get {
                return ResourceManager.GetString("FailedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway Settings Not Found.
        /// </summary>
        public static string GatewaySettingsNotFound {
            get {
                return ResourceManager.GetString("GatewaySettingsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Bill List From Database.
        /// </summary>
        public static string GetBillListFromDatabase {
            get {
                return ResourceManager.GetString("GetBillListFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Payment List.
        /// </summary>
        public static string GetPaymentList {
            get {
                return ResourceManager.GetString("GetPaymentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Gateway Settings.
        /// </summary>
        public static string LoadGatewaySettings {
            get {
                return ResourceManager.GetString("LoadGatewaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Payment Files.
        /// </summary>
        public static string LoadPaymentFiles {
            get {
                return ResourceManager.GetString("LoadPaymentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Payments: {0}, Already Paid: {1}, Not Found: {2}, Failed Pay: {3}..
        /// </summary>
        public static string PaymentResult {
            get {
                return ResourceManager.GetString("PaymentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Payment File.
        /// </summary>
        public static string ProcessPaymentFile {
            get {
                return ResourceManager.GetString("ProcessPaymentFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped Because of Previous Errors..
        /// </summary>
        public static string Skipped {
            get {
                return ResourceManager.GetString("Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Database.
        /// </summary>
        public static string UpdateDatabase {
            get {
                return ResourceManager.GetString("UpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Bill Lists.
        /// </summary>
        public static string UploadBillLists {
            get {
                return ResourceManager.GetString("UploadBillLists", resourceCulture);
            }
        }
    }
}
