//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SMSHints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SMSHints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Pages.SMSHints", typeof(SMSHints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Issue Date.
        /// </summary>
        public static string billIssueDate {
            get {
                return ResourceManager.GetString("billIssueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Total.
        /// </summary>
        public static string billTotal {
            get {
                return ResourceManager.GetString("billTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string cardNo {
            get {
                return ResourceManager.GetString("cardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone No.
        /// </summary>
        public static string contactPhoneNo {
            get {
                return ResourceManager.GetString("contactPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string expirationDate {
            get {
                return ResourceManager.GetString("expirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Months.
        /// </summary>
        public static string extendedMonths {
            get {
                return ResourceManager.GetString("extendedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation Address.
        /// </summary>
        public static string installationAddress {
            get {
                return ResourceManager.GetString("installationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Payment Day.
        /// </summary>
        public static string lastPaymentDay {
            get {
                return ResourceManager.GetString("lastPaymentDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quota Price.
        /// </summary>
        public static string lastQuotaPrice {
            get {
                return ResourceManager.GetString("lastQuotaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Quota Total.
        /// </summary>
        public static string lastQuotaTotal {
            get {
                return ResourceManager.GetString("lastQuotaTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Password.
        /// </summary>
        public static string onlinePassword {
            get {
                return ResourceManager.GetString("onlinePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Limit.
        /// </summary>
        public static string rateLimit {
            get {
                return ResourceManager.GetString("rateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.
        /// </summary>
        public static string referenceNo {
            get {
                return ResourceManager.GetString("referenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Days.
        /// </summary>
        public static string remainingDays {
            get {
                return ResourceManager.GetString("remainingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Quota.
        /// </summary>
        public static string remainingQuota {
            get {
                return ResourceManager.GetString("remainingQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residence Address.
        /// </summary>
        public static string residenceAddress {
            get {
                return ResourceManager.GetString("residenceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Quota Max Price.
        /// </summary>
        public static string smartQuotaMaxPrice {
            get {
                return ResourceManager.GetString("smartQuotaMaxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Quota Unit.
        /// </summary>
        public static string smartQuotaUnit {
            get {
                return ResourceManager.GetString("smartQuotaUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Quota Unit Price.
        /// </summary>
        public static string smartQuotaUnitPrice {
            get {
                return ResourceManager.GetString("smartQuotaUnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Code.
        /// </summary>
        public static string smsCode {
            get {
                return ResourceManager.GetString("smsCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Name.
        /// </summary>
        public static string subscriberName {
            get {
                return ResourceManager.GetString("subscriberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber No.
        /// </summary>
        public static string subscriberNo {
            get {
                return ResourceManager.GetString("subscriberNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber Service Name.
        /// </summary>
        public static string subscriberServiceName {
            get {
                return ResourceManager.GetString("subscriberServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        public static string totalCredit {
            get {
                return ResourceManager.GetString("totalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
