//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FreeRadius {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FreeRadius() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Model.FreeRadius", typeof(FreeRadius).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Password.
        /// </summary>
        public static string ApiPassword {
            get {
                return ResourceManager.GetString("ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Username.
        /// </summary>
        public static string ApiUsername {
            get {
                return ResourceManager.GetString("ApiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Period.
        /// </summary>
        public static string BillPeriodDay {
            get {
                return ResourceManager.GetString("BillPeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Burst Rate.
        /// </summary>
        public static string DownloadBurstRate {
            get {
                return ResourceManager.GetString("DownloadBurstRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Burst Threshold.
        /// </summary>
        public static string DownloadBurstThreshold {
            get {
                return ResourceManager.GetString("DownloadBurstThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Burst Time.
        /// </summary>
        public static string DownloadBurstTime {
            get {
                return ResourceManager.GetString("DownloadBurstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Rate.
        /// </summary>
        public static string DownloadRate {
            get {
                return ResourceManager.GetString("DownloadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP free start hour.
        /// </summary>
        public static string FUPEndHour {
            get {
                return ResourceManager.GetString("FUPEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Free End Hour.
        /// </summary>
        public static string FUPFreeEndHour {
            get {
                return ResourceManager.GetString("FUPFreeEndHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Free Start Hour.
        /// </summary>
        public static string FUPFreeStartHour {
            get {
                return ResourceManager.GetString("FUPFreeStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Rate Limit.
        /// </summary>
        public static string FUPRateLimit {
            get {
                return ResourceManager.GetString("FUPRateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Period.
        /// </summary>
        public static string FUPResetDay {
            get {
                return ResourceManager.GetString("FUPResetDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP free end hour.
        /// </summary>
        public static string FUPStartHour {
            get {
                return ResourceManager.GetString("FUPStartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Quotes Limit.
        /// </summary>
        public static string FUPTotalLimit {
            get {
                return ResourceManager.GetString("FUPTotalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Traffic Limit.
        /// </summary>
        public static string FUPTrafficLimit {
            get {
                return ResourceManager.GetString("FUPTrafficLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUP Usage.
        /// </summary>
        public static string FUPUsedBytes {
            get {
                return ResourceManager.GetString("FUPUsedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Grace Period.
        /// </summary>
        public static string GracePeriod {
            get {
                return ResourceManager.GetString("GracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has FUP.
        /// </summary>
        public static string HasFUP {
            get {
                return ResourceManager.GetString("HasFUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string NasIP {
            get {
                return ResourceManager.GetString("NasIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string NasName {
            get {
                return ResourceManager.GetString("NasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Secret.
        /// </summary>
        public static string NasSecret {
            get {
                return ResourceManager.GetString("NasSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Name.
        /// </summary>
        public static string NasShortName {
            get {
                return ResourceManager.GetString("NasShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Type.
        /// </summary>
        public static string NasType {
            get {
                return ResourceManager.GetString("NasType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RADIUS Incoming Port.
        /// </summary>
        public static string RadiusIncomingPort {
            get {
                return ResourceManager.GetString("RadiusIncomingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Limit.
        /// </summary>
        public static string RateLimit {
            get {
                return ResourceManager.GetString("RateLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simultaneous Use.
        /// </summary>
        public static string SimultaneousUse {
            get {
                return ResourceManager.GetString("SimultaneousUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Burst Rate.
        /// </summary>
        public static string UploadBurstRate {
            get {
                return ResourceManager.GetString("UploadBurstRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Burst Threshold.
        /// </summary>
        public static string UploadBurstThreshold {
            get {
                return ResourceManager.GetString("UploadBurstThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Burst Time.
        /// </summary>
        public static string UploadBurstTime {
            get {
                return ResourceManager.GetString("UploadBurstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Rate.
        /// </summary>
        public static string UploadRate {
            get {
                return ResourceManager.GetString("UploadRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
