//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Localization.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Permissions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Permissions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Localization.Model.Permissions", typeof(Permissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Fees.
        /// </summary>
        public static string AdditionalFees {
            get {
                return ResourceManager.GetString("AdditionalFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Referral Discount.
        /// </summary>
        public static string AddReferralDiscount {
            get {
                return ResourceManager.GetString("AddReferralDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address APi Settings.
        /// </summary>
        public static string AddressSettings {
            get {
                return ResourceManager.GetString("AddressSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Special Offer.
        /// </summary>
        public static string AddSpecialOffer {
            get {
                return ResourceManager.GetString("AddSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Access.
        /// </summary>
        public static string ArchiveAccess {
            get {
                return ResourceManager.GetString("ArchiveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Payment Report.
        /// </summary>
        public static string AutomaticPaymentReport {
            get {
                return ResourceManager.GetString("AutomaticPaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Services.
        /// </summary>
        public static string BackgroundServices {
            get {
                return ResourceManager.GetString("BackgroundServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch EBill.
        /// </summary>
        public static string BatchEBill {
            get {
                return ResourceManager.GetString("BatchEBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Expiration Date Update.
        /// </summary>
        public static string BatchExpirationDateUpdate {
            get {
                return ResourceManager.GetString("BatchExpirationDateUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch SMS.
        /// </summary>
        public static string BatchSMS {
            get {
                return ResourceManager.GetString("BatchSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bills.
        /// </summary>
        public static string Bills {
            get {
                return ResourceManager.GetString("Bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Logs.
        /// </summary>
        public static string BTKLogs {
            get {
                return ResourceManager.GetString("BTKLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTK Settings.
        /// </summary>
        public static string BTKSettings {
            get {
                return ResourceManager.GetString("BTKSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center Settings.
        /// </summary>
        public static string CallCenterSettings {
            get {
                return ResourceManager.GetString("CallCenterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Bill.
        /// </summary>
        public static string CancelBill {
            get {
                return ResourceManager.GetString("CancelBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Clients.
        /// </summary>
        public static string CancelledClients {
            get {
                return ResourceManager.GetString("CancelledClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Clients Unpaid Bills.
        /// </summary>
        public static string CancelledClientsUnpaidBills {
            get {
                return ResourceManager.GetString("CancelledClientsUnpaidBills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Payment.
        /// </summary>
        public static string CancelPayment {
            get {
                return ResourceManager.GetString("CancelPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Desk Report.
        /// </summary>
        public static string CashDeskReport {
            get {
                return ResourceManager.GetString("CashDeskReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashiers.
        /// </summary>
        public static string Cashiers {
            get {
                return ResourceManager.GetString("Cashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Client Service.
        /// </summary>
        public static string ChangeClientService {
            get {
                return ResourceManager.GetString("ChangeClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change DSL No.
        /// </summary>
        public static string ChangeDSLNo {
            get {
                return ResourceManager.GetString("ChangeDSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Speed Profile.
        /// </summary>
        public static string ChangeSpeedProfile {
            get {
                return ResourceManager.GetString("ChangeSpeedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Static IP.
        /// </summary>
        public static string ChangeStaticIP {
            get {
                return ResourceManager.GetString("ChangeStaticIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Username.
        /// </summary>
        public static string ChangeUsername {
            get {
                return ResourceManager.GetString("ChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Count.
        /// </summary>
        public static string ClientCount {
            get {
                return ResourceManager.GetString("ClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Files.
        /// </summary>
        public static string ClientFiles {
            get {
                return ResourceManager.GetString("ClientFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client IDs.
        /// </summary>
        public static string ClientIDs {
            get {
                return ResourceManager.GetString("ClientIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Usage Report.
        /// </summary>
        public static string ClientUsageReport {
            get {
                return ResourceManager.GetString("ClientUsageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close NAS Connections.
        /// </summary>
        public static string CloseNASConnections {
            get {
                return ResourceManager.GetString("CloseNASConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Setup Task.
        /// </summary>
        public static string CloseSetupTask {
            get {
                return ResourceManager.GetString("CloseSetupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        public static string Commitment {
            get {
                return ResourceManager.GetString("Commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment Report.
        /// </summary>
        public static string CommitmentReport {
            get {
                return ResourceManager.GetString("CommitmentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Bill.
        /// </summary>
        public static string CreateBill {
            get {
                return ResourceManager.GetString("CreateBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Setup Task.
        /// </summary>
        public static string CreateSetupTask {
            get {
                return ResourceManager.GetString("CreateSetupTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Support Request.
        /// </summary>
        public static string CreateSupportRequest {
            get {
                return ResourceManager.GetString("CreateSupportRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Setup Service.
        /// </summary>
        public static string CustomerSetupService {
            get {
                return ResourceManager.GetString("CustomerSetupService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Setup Users.
        /// </summary>
        public static string CustomerSetupUsers {
            get {
                return ResourceManager.GetString("CustomerSetupUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Website Settings.
        /// </summary>
        public static string CustomerWebsiteSettings {
            get {
                return ResourceManager.GetString("CustomerWebsiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect User.
        /// </summary>
        public static string DisconnectUser {
            get {
                return ResourceManager.GetString("DisconnectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Report.
        /// </summary>
        public static string DiscountReport {
            get {
                return ResourceManager.GetString("DiscountReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Settings.
        /// </summary>
        public static string DomainSettings {
            get {
                return ResourceManager.GetString("DomainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Bill Tax Details.
        /// </summary>
        public static string DownloadBillsTaxDetails {
            get {
                return ResourceManager.GetString("DownloadBillsTaxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Subscriber List.
        /// </summary>
        public static string DownloadSubscriberList {
            get {
                return ResourceManager.GetString("DownloadSubscriberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Bill.
        /// </summary>
        public static string EBill {
            get {
                return ResourceManager.GetString("EBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Client Files.
        /// </summary>
        public static string EditClientFiles {
            get {
                return ResourceManager.GetString("EditClientFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit ID Card.
        /// </summary>
        public static string EditIDCard {
            get {
                return ResourceManager.GetString("EditIDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notes.
        /// </summary>
        public static string EditNotes {
            get {
                return ResourceManager.GetString("EditNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externally Available Tariffs.
        /// </summary>
        public static string ExternallyAvailableTariffs {
            get {
                return ResourceManager.GetString("ExternallyAvailableTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager Settings.
        /// </summary>
        public static string FileManagerSettings {
            get {
                return ResourceManager.GetString("FileManagerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Cancellation.
        /// </summary>
        public static string ForceCancellation {
            get {
                return ResourceManager.GetString("ForceCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Change Service.
        /// </summary>
        public static string ForceChangeService {
            get {
                return ResourceManager.GetString("ForceChangeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Freeze.
        /// </summary>
        public static string ForceFreeze {
            get {
                return ResourceManager.GetString("ForceFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Unfreeze.
        /// </summary>
        public static string ForceUnfreeze {
            get {
                return ResourceManager.GetString("ForceUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Fault Query.
        /// </summary>
        public static string GeneralFaultQuery {
            get {
                return ResourceManager.GetString("GeneralFaultQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Support Request Change.
        /// </summary>
        public static string GlobalSupportRequestChange {
            get {
                return ResourceManager.GetString("GlobalSupportRequestChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Support Request Read.
        /// </summary>
        public static string GlobalSupportRequestRead {
            get {
                return ResourceManager.GetString("GlobalSupportRequestRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore TCK Validation.
        /// </summary>
        public static string IgnoreTCKValidation {
            get {
                return ResourceManager.GetString("IgnoreTCKValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure Service.
        /// </summary>
        public static string InfrastructureService {
            get {
                return ResourceManager.GetString("InfrastructureService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPDR Report.
        /// </summary>
        public static string IPDRReport {
            get {
                return ResourceManager.GetString("IPDRReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Quality Service.
        /// </summary>
        public static string LineQualityService {
            get {
                return ResourceManager.GetString("LineQualityService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Credit.
        /// </summary>
        public static string ManageCredit {
            get {
                return ResourceManager.GetString("ManageCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobilExpress Settings.
        /// </summary>
        public static string MobilExpressSettings {
            get {
                return ResourceManager.GetString("MobilExpressSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Cashiers.
        /// </summary>
        public static string ModifyCashiers {
            get {
                return ResourceManager.GetString("ModifyCashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Client IDs.
        /// </summary>
        public static string ModifyClientIDs {
            get {
                return ResourceManager.GetString("ModifyClientIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Clients.
        /// </summary>
        public static string ModifyClients {
            get {
                return ResourceManager.GetString("ModifyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Expiration Date.
        /// </summary>
        public static string ModifyExpirationDate {
            get {
                return ResourceManager.GetString("ModifyExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Groups.
        /// </summary>
        public static string ModifyGroups {
            get {
                return ResourceManager.GetString("ModifyGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Services.
        /// </summary>
        public static string ModifyServices {
            get {
                return ResourceManager.GetString("ModifyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Bill Report.
        /// </summary>
        public static string MonthlyBillReport {
            get {
                return ResourceManager.GetString("MonthlyBillReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAS.
        /// </summary>
        public static string NAS {
            get {
                return ResourceManager.GetString("NAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Payment Gateways.
        /// </summary>
        public static string OfflinePaymentGateways {
            get {
                return ResourceManager.GetString("OfflinePaymentGateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Payments.
        /// </summary>
        public static string OfflinePayments {
            get {
                return ResourceManager.GetString("OfflinePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Clients.
        /// </summary>
        public static string OnlineClients {
            get {
                return ResourceManager.GetString("OnlineClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Settings.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner API Settings.
        /// </summary>
        public static string PartnerAPISettings {
            get {
                return ResourceManager.GetString("PartnerAPISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Services.
        /// </summary>
        public static string PaymentServices {
            get {
                return ResourceManager.GetString("PaymentServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Templates.
        /// </summary>
        public static string PDFTemplates {
            get {
                return ResourceManager.GetString("PDFTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Sale.
        /// </summary>
        public static string QuotaSale {
            get {
                return ResourceManager.GetString("QuotaSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Settings.
        /// </summary>
        public static string QuotaSettings {
            get {
                return ResourceManager.GetString("QuotaSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius Settings.
        /// </summary>
        public static string RadiusSettings {
            get {
                return ResourceManager.GetString("RadiusSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Discount Report.
        /// </summary>
        public static string ReferralDiscountReport {
            get {
                return ResourceManager.GetString("ReferralDiscountReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Special Offer Usage.
        /// </summary>
        public static string ReferralSpecialOfferUsage {
            get {
                return ResourceManager.GetString("ReferralSpecialOfferUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risky Clients.
        /// </summary>
        public static string RiskyClients {
            get {
                return ResourceManager.GetString("RiskyClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Settings.
        /// </summary>
        public static string SchedulerSettings {
            get {
                return ResourceManager.GetString("SchedulerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email To Client.
        /// </summary>
        public static string SendEmailToClient {
            get {
                return ResourceManager.GetString("SendEmailToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Client Count.
        /// </summary>
        public static string ServicesClientCount {
            get {
                return ResourceManager.GetString("ServicesClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Task Service Fee.
        /// </summary>
        public static string SetupTaskServiceFee {
            get {
                return ResourceManager.GetString("SetupTaskServiceFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip TCK Validation.
        /// </summary>
        public static string SkipTCKValidation {
            get {
                return ResourceManager.GetString("SkipTCKValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Settings.
        /// </summary>
        public static string SMSSettings {
            get {
                return ResourceManager.GetString("SMSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Texts.
        /// </summary>
        public static string SMSTexts {
            get {
                return ResourceManager.GetString("SMSTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offers.
        /// </summary>
        public static string SpecialOffers {
            get {
                return ResourceManager.GetString("SpecialOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static IP Report.
        /// </summary>
        public static string StaticIPReport {
            get {
                return ResourceManager.GetString("StaticIPReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber State.
        /// </summary>
        public static string SubscriberState {
            get {
                return ResourceManager.GetString("SubscriberState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Requests.
        /// </summary>
        public static string SupportRequests {
            get {
                return ResourceManager.GetString("SupportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Request Settings.
        /// </summary>
        public static string SupportRequestSettings {
            get {
                return ResourceManager.GetString("SupportRequestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string SystemLogs {
            get {
                return ResourceManager.GetString("SystemLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs Report.
        /// </summary>
        public static string SystemLogsReport {
            get {
                return ResourceManager.GetString("SystemLogsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Taxes {
            get {
                return ResourceManager.GetString("Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Services.
        /// </summary>
        public static string TelekomServices {
            get {
                return ResourceManager.GetString("TelekomServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Tariffs.
        /// </summary>
        public static string TelekomTariffs {
            get {
                return ResourceManager.GetString("TelekomTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Work Order Edits.
        /// </summary>
        public static string TelekomWorkOrderEdits {
            get {
                return ResourceManager.GetString("TelekomWorkOrderEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom Work Orders.
        /// </summary>
        public static string TelekomWorkOrders {
            get {
                return ResourceManager.GetString("TelekomWorkOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Download/Upload.
        /// </summary>
        public static string TotalDownloadUpload {
            get {
                return ResourceManager.GetString("TotalDownloadUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport Subscription.
        /// </summary>
        public static string TransportSubscription {
            get {
                return ResourceManager.GetString("TransportSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual POS Settings.
        /// </summary>
        public static string VPOSSettings {
            get {
                return ResourceManager.GetString("VPOSSettings", resourceCulture);
            }
        }
    }
}
