//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NASVerticalDSLIPMap
    {
        public int NASID { get; set; }
        public string LocalIPPools { get; set; }
        public string DSLLineIPs { get; set; }
    
        public virtual NAS NAS { get; set; }
    }
}
