//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerCollection()
        {
            this.CustomerSetupTasks = new HashSet<CustomerSetupTask>();
            this.PartnerRegisteredSubscriptions = new HashSet<PartnerRegisteredSubscription>();
        }
    
        public long ID { get; set; }
        public int PartnerID { get; set; }
        public int CreatorID { get; set; }
        public Nullable<int> PayerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual AppUser CreatorUser { get; set; }
        public virtual AppUser PayerUser { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSetupTask> CustomerSetupTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRegisteredSubscription> PartnerRegisteredSubscriptions { get; set; }
    }
}
