//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportRequestProgress
    {
        public long ID { get; set; }
        public long SupportRequestID { get; set; }
        public System.DateTime Date { get; set; }
        public string Message { get; set; }
        public bool IsVisibleToCustomer { get; set; }
    
        public virtual SupportRequest SupportRequest { get; set; }
    }
}
