//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.DB.Utilities.ComplexOperations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistrationValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.DB.Utilities.ComplexOperations.Resources.RegistrationValidationMessages", typeof(RegistrationValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card validation failed..
        /// </summary>
        public static string IDCardValidationFailed {
            get {
                return ResourceManager.GetString("IDCardValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data for this customer type..
        /// </summary>
        public static string InsufficientDataForCustomerType {
            get {
                return ResourceManager.GetString("InsufficientDataForCustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid added fees..
        /// </summary>
        public static string InvalidAddedFees {
            get {
                return ResourceManager.GetString("InvalidAddedFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid billing period..
        /// </summary>
        public static string InvalidBillingPeriod {
            get {
                return ResourceManager.GetString("InvalidBillingPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Discount Type..
        /// </summary>
        public static string InvalidDiscountType {
            get {
                return ResourceManager.GetString("InvalidDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain..
        /// </summary>
        public static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Fee Type..
        /// </summary>
        public static string InvalidFeeType {
            get {
                return ResourceManager.GetString("InvalidFeeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid groups..
        /// </summary>
        public static string InvalidGroups {
            get {
                return ResourceManager.GetString("InvalidGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid partner..
        /// </summary>
        public static string InvalidPartner {
            get {
                return ResourceManager.GetString("InvalidPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference No..
        /// </summary>
        public static string InvalidReferenceNo {
            get {
                return ResourceManager.GetString("InvalidReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Special Offer..
        /// </summary>
        public static string InvalidSpecialOffer {
            get {
                return ResourceManager.GetString("InvalidSpecialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tariff..
        /// </summary>
        public static string InvalidTariff {
            get {
                return ResourceManager.GetString("InvalidTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tariff for partner..
        /// </summary>
        public static string InvalidTariffForPartner {
            get {
                return ResourceManager.GetString("InvalidTariffForPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tariff Type For Referral Discount..
        /// </summary>
        public static string InvalidTariffTypeForReferralDiscount {
            get {
                return ResourceManager.GetString("InvalidTariffTypeForReferralDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom tariff is invalid. (PacketCode: {0}, TariffCode: {1}).
        /// </summary>
        public static string InvalidTelekomTariff {
            get {
                return ResourceManager.GetString("InvalidTelekomTariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telekom info is not valid for this domain..
        /// </summary>
        public static string TelekomInfoNotValidForDomain {
            get {
                return ResourceManager.GetString("TelekomInfoNotValidForDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not syncronize with Telekom. ({0}).
        /// </summary>
        public static string TelekomSyncError {
            get {
                return ResourceManager.GetString("TelekomSyncError", resourceCulture);
            }
        }
    }
}
