//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.DB.Utilities.ComplexOperations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StateChanges {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StateChanges() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.DB.Utilities.ComplexOperations.Resources.StateChanges", typeof(StateChanges).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager error.
        /// </summary>
        public static string FileManagerError {
            get {
                return ResourceManager.GetString("FileManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription attachments validation for transition operation failed..
        /// </summary>
        public static string InvalidAttachmentsForTransition {
            get {
                return ResourceManager.GetString("InvalidAttachmentsForTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid freeze duration..
        /// </summary>
        public static string InvalidFreezeDuration {
            get {
                return ResourceManager.GetString("InvalidFreezeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring subscription domain does not match..
        /// </summary>
        public static string InvalidTransferringSubscriptionDomain {
            get {
                return ResourceManager.GetString("InvalidTransferringSubscriptionDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring subscription has no valid Telekom info..
        /// </summary>
        public static string InvalidTransferringSubscriptionTelekomInfo {
            get {
                return ResourceManager.GetString("InvalidTransferringSubscriptionTelekomInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition subscription does not have XDSL no..
        /// </summary>
        public static string InvalidTransitionXDSLNo {
            get {
                return ResourceManager.GetString("InvalidTransitionXDSLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred to {0} subscription no..
        /// </summary>
        public static string TransferCancellationReason {
            get {
                return ResourceManager.GetString("TransferCancellationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring subscription not found..
        /// </summary>
        public static string TransferingSubscriptionNotFound {
            get {
                return ResourceManager.GetString("TransferingSubscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was successful but transition FTP error occured. Try to upload transition files again..
        /// </summary>
        public static string TransitionFTPError {
            get {
                return ResourceManager.GetString("TransitionFTPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring subscription is not active..
        /// </summary>
        public static string TrasferringSubscriptionNotAktive {
            get {
                return ResourceManager.GetString("TrasferringSubscriptionNotAktive", resourceCulture);
            }
        }
    }
}
